const revision = new URL(import.meta.url).searchParams.get('v') || 'dev';
const { loadTournamentContext } = await import(`../event-context.js?v=${encodeURIComponent(revision)}`);
await loadTournamentContext();
const { watchAuth, login, logout, getCurrentProfile, watchMembership, watchRefereeBoard, watchMatches, watchCheckins, publishMatch, requestMatchPromotion } = await import(`../firebase-sync.js?v=${encodeURIComponent(revision)}`);

(() => {
  'use strict';
  const config = window.TOURNAMENT_CONFIG;
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
  document.querySelector('.field-brand img').src = config.brand.logo; document.querySelector('.field-header-actions>a').href = window.MATCHDAY_EVENT_URL('../control.html');
  let state, email = '', activeId = null, tick, cloudUser = null, pendingPromotionId = null, matchWriteSequence = 0, latestMatchDocsReady = false;
  const pendingMatchWrites = new Map(), matchWriteChains = new Map(), latestMatchDocs = new Map();

  function load() { try { return JSON.parse(localStorage.getItem(config.storageKey)); } catch (_) { return null; } }
  function save() {
    state.updatedAt = new Date().toISOString();
    localStorage.setItem(config.storageKey, JSON.stringify(state));
    if (!cloudUser || !activeId) return;
    const matchId = activeId, sequence = ++matchWriteSequence;
    const live = structuredClone(state.liveScoring?.[matchId] || null), score = structuredClone(state.scores?.[matchId] || null);
    pendingMatchWrites.set(matchId, sequence);
    const chain=(matchWriteChains.get(matchId)||Promise.resolve()).catch(()=>{}).then(()=>publishMatch(matchId,live,score));matchWriteChains.set(matchId,chain);chain
      .catch(() => toast('Saved locally. Cloud sync failed.'))
      .finally(() => { if (pendingMatchWrites.get(matchId) === sequence) pendingMatchWrites.delete(matchId); if(matchWriteChains.get(matchId)===chain)matchWriteChains.delete(matchId); });
  }
  function players(category, code) { const p = state.pairs[`${category}|${code}`] || state.pairs[code] || {}; return [p.player1 || 'Player 1', p.player2 || 'Player 2']; }
  function pairRecord(category, code) { return state.pairs?.[`${category}|${code}`] || state.pairs?.[category]?.[code] || {}; }
  function pairLabel(category, code) { return pairRecord(category, code)?.pairCode || 'PAIR'; }
  function matchLabel(match) { const number = Number(match?.scheduleNumber); return number > 0 ? `M${number}` : 'MATCH'; }
  function affiliationId(match, side) { const pair = pairRecord(match.category, match[side]); return match?.[`${side}AffiliationId`] ?? pair.affiliationId ?? pair.club ?? (side === 'a' ? 'ocpc' : 'rebels'); }
  function affiliation(match, side) { const id = affiliationId(match, side); return (config.affiliations || config.clubs || []).find(item => item.id === id) || { id, short: id || (side === 'a' ? 'Side A' : 'Side B'), name: id || (side === 'a' ? 'Side A' : 'Side B') }; }
  function playerPhoto(category, code, clubId, index) { const checkin = Object.values(state.checkins || {}).find(item => item.category === category && item.pair === code && item.club === clubId && Number(item.playerIndex) === index); return checkin?.photoURL || checkin?.photoThumb || ''; }
  function names(category, code) { const item=pairRecord(category,code),members=players(category,code);return item.name||item.names||(item.teamName?`${item.teamName} (${members.join(' & ')})`:members.join(' / ')); }
  function prefix(category) { if (category === 'Novice') return 'NOV'; if (category === 'Low Intermediate') return 'LOW'; if (category === 'High Intermediate') return 'HIGH'; return String(category).replace(/[^a-z0-9 ]/gi,'').split(/\s+/).filter(Boolean).map(word=>word[0]).join('').slice(0,4).toUpperCase() || 'CAT'; }
  function toast(message) { const el = $('#officialToast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 1800); }
  function clock(seconds) { return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; }
  function elapsed(live) { return (live.elapsed || 0) + (live.running && live.startedAt ? Math.max(0, Math.floor((Date.now() - live.startedAt) / 1000)) : 0); }
  function defaultLive() { return { a: 0, b: 0, serving: 'a', server: 2, serverPlayer: 0, basePlayer: 0, timeouts: { a: 0, b: 0 }, medical: 0, technicalTimeouts: 0, refereeTimeouts: 0, equipmentTimeouts: 0, interruption: null, endsChanged: false, running: false, startedAt: null, elapsed: 0, complete: false, pregame: { complete: false, winner: 'a', firstChoice: 'serve', courtEnd: 'North / Court A', otherChoice: 'receive', finalChoice: 'serve' }, log: [], history: [] }; }
  function liveFor(match) { state.liveScoring ||= {}; return state.liveScoring[match.id] ||= defaultLive(); }
  function addLog(live, text) { live.log.unshift({ at: new Date().toISOString(), text }); live.log = live.log.slice(0, 30); }
  function activeMatch() { return state.matches.find(match => match.id === activeId); }
  function matchRules(match) {
    if (state?.competitionType === 'standard' || config.competitionType === 'standard') {
      if (match?.medal === 'gold') return { mode:'championship', label:'Championship Final', scoring:'side-out', twoServes:true, target:11, winBy:2, hardCap:15, suddenDeathAt:null, timer:false, timerSeconds:0 };
      return { mode:'preliminary', label:'Preliminary', scoring:'side-out', twoServes:true, target:11, winBy:2, hardCap:11, suddenDeathAt:10, timer:true, timerSeconds:(Number(state?.standardScheduling?.matchMinutes) || 18) * 60 };
    }
    return state.matchSettings?.[match.id] || { mode: 'round-robin', label: 'Round Robin', target: 11, suddenDeathAt: 10, timer: true };
  }
  function validFinalScore(live, rules) {
    const high = Math.max(Number(live.a), Number(live.b)), low = Math.min(Number(live.a), Number(live.b));
    if (high === low || high > Number(rules.hardCap || Infinity)) return false;
    const regulation = rules.mode === 'championship'
      ? high === 15 || (high >= 11 && high - low >= 2)
      : rules.mode === 'preliminary'
        ? high === 11 && (low <= 9 || low === 10)
        : (high >= rules.target && high <= Math.max(rules.target, rules.suddenDeathAt) && high - low >= 2 || high === rules.suddenDeathAt + 1 && low === rules.suddenDeathAt);
    const timed = rules.mode === 'preliminary' && rules.timer !== false && elapsed(live) >= Number(rules.timerSeconds || config.scoring?.targetSeconds || 900) && high !== low;
    return regulation || timed;
  }
  function endsChangeScore(rules) { return rules.target === 11 ? 6 : rules.target === 15 ? 8 : Math.ceil(rules.target / 2); }
  function activeCourtFor(matchId) { return Number(Object.keys(state.courts || {}).find(courtNo => state.courts[courtNo]?.matchId === matchId)) || 0; }
  function nextForCourt(courtNo) {
    if (state.courtAvailability?.[courtNo] === false) return '';
    if (state.courts?.[courtNo]?.matchId) return '';
    const active = new Set(Object.values(state.courts || {}).map(court => court.matchId).filter(Boolean));
    return state.matches.filter(match => Number(match.court) === Number(courtNo) && !active.has(match.id) && !state.scores?.[match.id]).sort((a, b) => Number(a.startMinutes) - Number(b.startMinutes) || String(a.id).localeCompare(String(b.id)))[0]?.id || '';
  }
  function eligibleCourtFor(matchId) { return Number(Object.keys(state.courts || {}).find(courtNo => state.courtAvailability?.[courtNo] !== false && nextForCourt(Number(courtNo)) === matchId)) || 0; }

  function renderAssignments() {
    state = load(); if (!state) return;
    const matches = state.matches.filter(match => state.refereeAssignments?.[match.id] === email);
    const statusFor = match => state.scores[match.id] ? 'complete' : state.liveScoring?.[match.id] ? 'live' : 'ready';
    const statusOrder = { live: 0, ready: 1, complete: 2 };
    const ordered = [...matches].sort((a, b) => statusOrder[statusFor(a)] - statusOrder[statusFor(b)] || String(a.time).localeCompare(String(b.time)));
    const counts = ordered.reduce((all, match) => { all[statusFor(match)]++; return all; }, { live: 0, ready: 0, complete: 0 });
    $('#assignmentSummary').hidden = false; $('#assignmentSummary').innerHTML = `<span><b>${counts.live}</b> Live</span><span><b>${counts.ready}</b> Upcoming</span><span><b>${counts.complete}</b> Complete</span>`;
    const courtCards = Object.keys(state.courts || {}).map(Number).filter(courtNo => state.courtAvailability?.[courtNo] !== false).map(courtNo => { const court = state.courts?.[courtNo] || {}, match = state.matches.find(item => item.id === court.matchId), next = !match ? state.matches.find(item => item.id === nextForCourt(courtNo)) : null, shown = match || next, assigned = shown && state.refereeAssignments?.[shown.id] === email; if (!shown) return `<article class="referee-court-card vacant"><header><b>Court ${courtNo}</b><span>Vacant</span></header><div><strong>Available court</strong><small>No scheduled match remains</small></div></article>`; const live = match ? state.liveScoring?.[shown.id] : null, score = match && (state.scores?.[shown.id] || live), status = match ? state.scores?.[shown.id] ? 'Final' : live?.running ? 'Live' : live ? 'Ready' : 'On court' : 'Up next'; return `<article class="referee-court-card ${assigned ? 'assigned' : ''} ${next ? 'vacant' : ''}"><header><b>Court ${courtNo}</b><span>${next ? 'Vacant · Up next' : assigned ? 'Assigned to you' : status}</span></header><div><small>${esc(shown.category)} · ${esc(matchLabel(shown))}</small><strong>${esc(names(shown.category, shown.a))}</strong><em>vs</em><strong>${esc(names(shown.category, shown.b))}</strong>${score ? `<b class="referee-court-score">${score.a || 0}–${score.b || 0}</b>` : ''}${assigned ? `<button class="action" data-open-match="${shown.id}">${next ? 'Begin officiating · Promote match' : 'Open live scorekeeper'}</button>` : `<button class="action alt" disabled>${next ? 'Next match · referee not assigned' : 'View only'}</button>`}</div></article>`; }).join('');
    const activeIds = new Set(Object.values(state.courts || {}).map(court => court.matchId).filter(Boolean));
    const assignedList = ordered.filter(match => !activeIds.has(match.id)).map(match => {
      const live = state.liveScoring?.[match.id], final = state.scores[match.id];
      const status = final ? `Final ${final.a}-${final.b}` : live ? `Live ${live.a}-${live.b}` : 'Ready';
      const activeCourt = activeCourtFor(match.id), eligibleCourt = eligibleCourtFor(match.id), eligible = Boolean(activeCourt || eligibleCourt || final);
      return `<article class="official-match assignment-card assignment-${statusFor(match)}"><div><div class="match-meta"><span>${esc(match.category)}</span><b>${esc(matchLabel(match))}</b><span>${esc(match.time || `Wave ${match.wave}`)} · Court ${match.court || 'TBA'}</span></div><div class="match-pairs"><div><strong>${esc(pairLabel(match.category, match.a))}</strong><small>${esc(names(match.category, match.a))}</small></div><b>VS</b><div><strong>${esc(pairLabel(match.category, match.b))}</strong><small>${esc(names(match.category, match.b))}</small></div></div></div><div class="assignment-action"><span class="live-status">${activeCourt ? `On Court ${activeCourt}` : eligibleCourt ? `Up next · Court ${eligibleCourt}` : status}</span><button class="action" data-open-match="${match.id}" ${eligible ? '' : 'disabled'}>${final ? 'Review match' : activeCourt ? live ? 'Resume scorekeeper' : 'Open scorekeeper' : eligibleCourt ? 'Begin officiating · Promote' : 'Waiting for court'}</button></div></article>`;
    }).join('');
    $('#matchList').innerHTML = `<section class="referee-court-board"><div class="referee-board-title"><span class="eyebrow">Live venue</span><h2>Courts now</h2><p>All courts are visible. Scoring opens only on matches assigned to your exact account email.</p></div><div class="referee-court-grid">${courtCards}</div></section><section class="referee-upcoming"><h2>Your next assignments</h2>${assignedList || '<div class="field-card"><p>No additional matches are assigned yet.</p></div>'}</section>`;
    $$('[data-open-match]').forEach(button => button.onclick = () => openMatch(button.dataset.openMatch));
  }

  async function openMatch(id) {
    const activeCourt = activeCourtFor(id); if (activeCourt || state.scores?.[id]) return enterScorekeeper(id);
    const courtNo = eligibleCourtFor(id); if (!courtNo) return toast('This assignment is not next for a vacant court yet.');
    pendingPromotionId = id; toast(`Promoting ${id} to Court ${courtNo}…`);
    try { await requestMatchPromotion(id, courtNo, email); } catch (_) { pendingPromotionId = null; toast('Match Control could not receive the promotion request.'); }
  }
  function enterScorekeeper(id) { activeId = id; pendingPromotionId = null; $('#assignmentView').hidden = true; $('#scorekeeperView').hidden = false; renderScorekeeper(); clearInterval(tick); tick = setInterval(updateClock, 1000); }
  function closeMatch() { activeId = null; clearInterval(tick); $('#scorekeeperView').hidden = true; $('#assignmentView').hidden = false; renderAssignments(); }
  function teamPanel(match, side, club, code, playerNames, live, category, rules) {
    const serving = live.serving === side, scoringReady = Boolean(live.running && !live.interruption?.active && !live.complete);
    const clubId = affiliationId(match, side), customTeam=pairRecord(category,code).teamName||'';
    return `<article class="score-team ${serving ? 'serving' : ''} ${scoringReady ? 'scoring-ready' : 'scoring-locked'}"><div class="team-heading"><span>${esc(club)}${customTeam?`<small>${esc(customTeam)}</small>`:''}</span><b>${esc(pairLabel(category, code))}</b></div><strong class="giant-score">${live[side]}</strong><div class="player-tags">${playerNames.map((name,index) => { const image = playerPhoto(category,code,clubId,index); return `<span class="${serving && live.serverPlayer === index ? 'server' : ''}">${image ? `<img src="${image}" alt="">` : '<i class="photo-placeholder"></i>'}<b>${esc(name)}</b></span>`; }).join('')}</div><button class="point-button" data-point="${side}" ${(rules.scoring === 'rally' || serving) && scoringReady ? '' : 'disabled'}>+ Point</button></article>`;
  }
  function teamName(side, match = activeMatch()) { const item = match && affiliation(match, side); return item?.short || item?.name || (side === 'a' ? 'Side A' : 'Side B'); }
  function renderPregame(match, live) {
    const pregame = live.pregame ||= defaultLive().pregame; pregame.winner ||= 'a'; const loser = pregame.winner === 'a' ? 'b' : 'a', chooser = teamName(pregame.winner), selectedChoice = { serve: 'Serve first', receive: 'Receive first', end: 'Choose starting end', defer: 'Defer first choice' }[pregame.firstChoice] || 'Choose an option';
    const rules = matchRules(match), ruleNote = rules.mode === 'championship' ? 'Championship Final: side-out scoring, two serves, first to 11, win by 2, with a 15-point maximum cap. No timer.' : 'Preliminary: side-out scoring, two serves, first to 11. At 10-10, the next rally decides the match.';
    $('#scorekeeperView').innerHTML = `<div class="pregame-shell"><button class="back-button pregame-back" id="backToMatches">← Assigned matches</button><span class="eyebrow">${esc(matchLabel(match))} · ${esc(match.category)}</span><h1>Pre-match setup</h1><p class="sub">First, record which club has the first choice. Then record what that club chooses before opening the scorekeeper.</p><section class="choice-card"><div class="setup-step"><span>Step 1</span><b>Choose the club with first choice</b></div><div class="choice-heading"><h2>Which side chooses first?</h2><p>The selected club is highlighted in green and shown as the first chooser below.</p></div><div class="first-choice-grid">${['a','b'].map(side => `<button type="button" data-first-club="${side}" class="first-choice-button ${pregame.winner === side ? 'selected' : ''}" aria-pressed="${pregame.winner === side}"><span class="choice-radio">${pregame.winner === side ? '✓' : ''}</span><span class="choice-team"><b>${esc(teamName(side))}</b><small>${esc(names(match.category, side === 'a' ? match.a : match.b))}</small></span><strong>${pregame.winner === side ? 'Chooses first' : 'Select this side'}</strong></button>`).join('')}</div><div class="choice-confirmation"><span class="choice-confirmation-icon">1</span><div><small>First chooser</small><b>${esc(chooser)}</b><span>${esc(selectedChoice)}</span></div></div><div class="setup-step"><span>Step 2</span><b>Record their choice</b></div><label class="first-choice-field">${esc(chooser)} chooses<select id="firstChoice"><option value="serve" ${pregame.firstChoice === 'serve' ? 'selected' : ''}>Serve first</option><option value="receive" ${pregame.firstChoice === 'receive' ? 'selected' : ''}>Receive first</option><option value="end" ${pregame.firstChoice === 'end' ? 'selected' : ''}>Choose starting end</option><option value="defer" ${pregame.firstChoice === 'defer' ? 'selected' : ''}>Defer first choice</option></select></label>${choiceFields(pregame, loser)}<div class="setup-final-check"><span>Ready to begin?</span><b>${esc(chooser)} · ${esc(selectedChoice)}</b><small>Review the selection with both pairs, then open live scoring.</small></div><button class="finish-match" id="confirmPregame">Confirm setup and open scorekeeper</button></section><aside class="rules-note"><b>Event scoring notice</b><p>${esc(ruleNote)}</p></aside></div>`;
    $('#backToMatches').onclick = closeMatch; $$('[data-first-club]').forEach(button=>button.onclick=()=>{pregame.winner=button.dataset.firstClub;save();renderPregame(match,live)}); $('#firstChoice').onchange = event => { pregame.firstChoice = event.target.value; save(); renderPregame(match, live); }; $$('[data-pregame-field]').forEach(input => input.onchange = () => { pregame[input.dataset.pregameField] = input.value; save(); if (input.dataset.rerender) renderPregame(match, live); }); $('#confirmPregame').onclick = confirmPregame;
  }
  function choiceFields(pregame, loser) {
    const endField = `<label>Starting court end<select data-pregame-field="courtEnd"><option ${pregame.courtEnd === 'North / Court A' ? 'selected' : ''}>North / Court A</option><option ${pregame.courtEnd === 'South / Court B' ? 'selected' : ''}>South / Court B</option></select></label>`;
    if (pregame.firstChoice === 'serve' || pregame.firstChoice === 'receive') return `<p>${teamName(loser)} receives the remaining choice of starting end.</p>${endField}`;
    if (pregame.firstChoice === 'end') return `${endField}<label>${teamName(loser)} chooses<select data-pregame-field="otherChoice"><option value="serve" ${pregame.otherChoice === 'serve' ? 'selected' : ''}>Serve first</option><option value="receive" ${pregame.otherChoice === 'receive' ? 'selected' : ''}>Receive first</option></select></label>`;
    return `<label>${teamName(loser)} receives first choice<select data-pregame-field="otherChoice" data-rerender="true"><option value="serve" ${pregame.otherChoice === 'serve' ? 'selected' : ''}>Serve first</option><option value="receive" ${pregame.otherChoice === 'receive' ? 'selected' : ''}>Receive first</option><option value="end" ${pregame.otherChoice === 'end' ? 'selected' : ''}>Choose starting end</option></select></label>${endField}${pregame.otherChoice === 'end' ? `<label>${teamName(pregame.winner)} then chooses<select data-pregame-field="finalChoice"><option value="serve" ${pregame.finalChoice === 'serve' ? 'selected' : ''}>Serve first</option><option value="receive" ${pregame.finalChoice === 'receive' ? 'selected' : ''}>Receive first</option></select></label>` : ''}`;
  }
  function confirmPregame() {
    const live = liveFor(activeMatch()), pregame = live.pregame, loser = pregame.winner === 'a' ? 'b' : 'a';
    if (pregame.firstChoice === 'serve') live.serving = pregame.winner;
    else if (pregame.firstChoice === 'receive') live.serving = loser;
    else if (pregame.firstChoice === 'end') live.serving = pregame.otherChoice === 'serve' ? loser : pregame.winner;
    else if (pregame.otherChoice === 'serve') live.serving = loser;
    else if (pregame.otherChoice === 'receive') live.serving = pregame.winner;
    else live.serving = pregame.finalChoice === 'serve' ? pregame.winner : loser;
    live.server = 2; live.serverPlayer = 0; live.basePlayer = 0; pregame.complete = true;
    addLog(live, `Pre-match choices confirmed. ${teamName(live.serving)} serves first; opening call 0-0-2.`); save(); renderScorekeeper();
  }
  function renderScorekeeper() {
    state = load(); const match = activeMatch(); if (!match) return closeMatch();
    const live = liveFor(match);
    if (!live.pregame?.complete) return renderPregame(match, live);
    const aPlayers = players(match.category, match.a), bPlayers = players(match.category, match.b), servingPlayers = live.serving === 'a' ? aPlayers : bPlayers, receivingPlayers = live.serving === 'a' ? bPlayers : aPlayers, final = state.scores[match.id], rules = matchRules(match), scoringReady = Boolean(live.running && !live.interruption?.active && !live.complete && !final), changeAt = endsChangeScore(rules), endsDue = !final && !live.endsChanged && Math.max(live.a, live.b) >= changeAt, winnerSide = validFinalScore(live, rules) ? (Number(live.a) > Number(live.b) ? 'a' : 'b') : '', winnerClub = winnerSide ? teamName(winnerSide) : '', winnerPair = winnerSide === 'a' ? names(match.category, match.a) : names(match.category, match.b), matchState = final ? 'Match complete' : live.interruption?.active ? 'Scoring paused during interruption' : live.running ? 'Scoring enabled' : live.elapsed ? 'Scoring locked · resume timer to continue' : 'Scoring locked · start timer first', timerAction = live.interruption?.active ? 'End interruption first' : live.running ? 'Pause match' : live.elapsed ? 'Resume match' : 'Start match';
    const flowOverlay = endsDue ? `<div class="referee-flow-overlay change-ends"><section><span>CHANGE ENDS</span><h2>Switch court ends</h2><strong>${changeAt}-point midpoint reached</strong><p>Pause play and confirm that both pairs have changed ends before the next serve.</p><button id="confirmEndsChanged">Players changed ends · Continue play</button></section></div>` : winnerSide && !final ? `<div class="referee-flow-overlay winner"><section><span>MATCH COMPLETE</span><h2>${esc(winnerClub)} wins</h2><strong>${live.a}-${live.b}</strong><p>${esc(winnerPair)}</p><button id="confirmWinningScore">Review score and collect signatures</button><button class="flow-secondary" id="undoWinningPoint">Undo last rally</button></section></div>` : '';
    $('#scorekeeperView').innerHTML = `
      <div class="scorekeeper-top"><button class="back-button" id="backToMatches">← Matches</button><div><span>${esc(matchLabel(match))} · ${esc(match.category)} · ${esc(rules.label)}</span><b>${esc(matchState)}</b></div><span class="header-clock">${rules.timer ? 'Match timer' : 'Match clock'} · <strong id="officialClock">${clock(elapsed(live))}</strong></span></div>
      <section class="match-start-banner ${scoringReady ? 'running' : final ? 'complete' : 'locked'}"><div><span>${final ? 'Match closed' : scoringReady ? 'Live scoring unlocked' : 'Start required before scoring'}</span><b>${esc(matchState)}</b><small>${final ? 'This result has been submitted.' : live.interruption?.active ? 'End the interruption to resume scoring.' : 'Point, fault, and result controls unlock only while the match timer is running.'}</small></div>${final ? '<span class="start-complete-mark">✓</span>' : `<button class="start-match-control ${scoringReady ? 'running' : ''}" id="timerToggle" ${live.interruption?.active ? 'disabled' : ''}><span>${timerAction}</span><strong id="startMatchClock">${clock(elapsed(live))}</strong></button>`}</section>
      <div class="serve-call"><span>Call the score</span><strong>${live.serving === 'a' ? live.a : live.b} - ${live.serving === 'a' ? live.b : live.a} - ${live.server}</strong><small>${esc(servingPlayers[live.serverPlayer])} serving for ${esc(teamName(live.serving))}</small></div>${live.interruption?.active ? `<div class="official-interruption ${['medical','technical'].includes(live.interruption.type) ? 'danger' : 'warning'}"><span>${esc(live.interruption.label)}</span><b id="officialInterruptionClock">${clock(elapsed(live.interruption))}</b><button id="endOfficialInterruption">End interruption</button></div>` : live.lastInterruption?.expired ? `<div class="official-interruption expired"><span>${esc(live.lastInterruption.label)} time is up</span><b>Resume play</b><button id="resumeAfterInterruption">Resume match</button></div>` : ''}
      <div class="live-scoreboard">${teamPanel(match, 'a', teamName('a', match), match.a, aPlayers, live, match.category, rules)}${teamPanel(match, 'b', teamName('b', match), match.b, bPlayers, live, match.category, rules)}</div>
      <div class="official-controls"><button class="control-button fault" id="faultButton" ${scoringReady ? '' : 'disabled'}><span>✕</span><b>Fault / next server</b><small>${scoringReady ? live.server === 1 ? 'Moves to server 2' : 'Awards side out' : 'Start the match timer first'}</small></button><button class="control-button undo" id="undoButton"><span>↶</span><b>Undo last action</b><small>Correct the previous tap</small></button></div>
      <div class="match-tools"><section><h3>Serving player</h3><div class="segmented"><button data-server-player="0" class="${live.serverPlayer === 0 ? 'active' : ''}">${esc(servingPlayers[0])}</button><button data-server-player="1" class="${live.serverPlayer === 1 ? 'active' : ''}">${esc(servingPlayers[1])}</button></div><h3 style="margin-top:16px">Receiving / base player</h3><div class="segmented"><button data-base-player="0" class="${live.basePlayer === 0 ? 'active' : ''}">${esc(receivingPlayers[0])}</button><button data-base-player="1" class="${live.basePlayer === 1 ? 'active' : ''}">${esc(receivingPlayers[1])}</button></div></section><section><h3>Guarded match interruptions</h3><div class="tool-buttons"><button data-timeout="a" ${!scoringReady || rules.mode === 'preliminary' || live.timeouts.a >= 1 ? 'disabled' : ''}>${esc(teamName('a'))} timeout <b>${rules.mode === 'preliminary' ? 'Not allowed' : `${live.timeouts.a}/1 · 60 sec`}</b></button><button data-timeout="b" ${!scoringReady || rules.mode === 'preliminary' || live.timeouts.b >= 1 ? 'disabled' : ''}>${esc(teamName('b'))} timeout <b>${rules.mode === 'preliminary' ? 'Not allowed' : `${live.timeouts.b}/1 · 60 sec`}</b></button><button id="medicalButton" ${scoringReady ? '' : 'disabled'}>Medical <b>${live.medical} · 5 min max</b></button><button id="technicalTimeoutButton" ${scoringReady ? '' : 'disabled'}>Technical <b>${live.technicalTimeouts || 0}</b></button><button id="refereeTimeoutButton" ${scoringReady ? '' : 'disabled'}>Referee timeout <b>${live.refereeTimeouts || 0}</b></button><button id="equipmentTimeoutButton" ${scoringReady ? '' : 'disabled'}>Equipment timeout <b>${live.equipmentTimeouts || 0}</b></button></div></section></div>
      <section class="rally-log"><h3>Match log</h3>${live.log.map(item => `<div><time>${new Date(item.at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time><span>${esc(item.text)}</span></div>`).join('')}</section>
      <button class="finish-match" id="finishButton" ${final || !scoringReady ? 'disabled' : ''}>${final ? `Submitted final: ${final.a}-${final.b}` : scoringReady ? 'Finish match and confirm result' : 'Start the match timer to finish'}</button><div id="confirmationSheet" hidden></div><div id="interruptionSheet" hidden></div>${flowOverlay}`;
    bindScorekeeper();
  }

  function snapshot(live) { return { a: live.a, b: live.b, serving: live.serving, server: live.server, serverPlayer: live.serverPlayer, basePlayer: live.basePlayer, timeouts: { ...live.timeouts }, medical: live.medical, technicalTimeouts: live.technicalTimeouts, refereeTimeouts: live.refereeTimeouts, equipmentTimeouts: live.equipmentTimeouts, interruption: live.interruption ? { ...live.interruption } : null, endsChanged: !!live.endsChanged }; }
  function transact(label, change) { const live = liveFor(activeMatch()), rules = matchRules(activeMatch()); live.history.push(snapshot(live)); change(live); addLog(live, label); if (validFinalScore(live, rules) && live.running) { live.elapsed = elapsed(live); live.running = false; live.startedAt = null; addLog(live, 'Finishing score reached; match timer paused'); } save(); renderScorekeeper(); }
  function scoringIsOpen() { const match = activeMatch(), live = match && liveFor(match); return Boolean(match && live?.running && !live.interruption?.active && !live.complete && !state.scores?.[match.id]); }
  function requireRunningMatch() { if (scoringIsOpen()) return true; toast('Start or resume the match timer before logging a score.'); return false; }
  function sideOut(live) { live.serving = live.serving === 'a' ? 'b' : 'a'; live.server = 1; live.serverPlayer = 0; }
  function bindScorekeeper() {
    $('#backToMatches').onclick = closeMatch; if ($('#timerToggle')) $('#timerToggle').onclick = toggleTimer;
    $$('[data-point]').forEach(button => button.onclick = () => { if (!requireRunningMatch()) return; transact(`${teamName(button.dataset.point)} scored`, live => { const rules = matchRules(activeMatch()), side = button.dataset.point, maximum = Number(rules.hardCap || Math.max(rules.target, Number(rules.suddenDeathAt || 0) + 1)); if (rules.scoring === 'rally') { if (live[side] < maximum) live[side]++; if (live.serving !== side) { live.serving = side; live.server = 1; live.serverPlayer = 0; } } else if (live.serving === side && live[side] < maximum) live[side]++; }); });
    $('#faultButton').onclick = () => { if (!requireRunningMatch()) return; transact('Fault called', live => { if (live.server === 1) { live.server = 2; live.serverPlayer = live.serverPlayer ? 0 : 1; } else sideOut(live); }); };
    $('#undoButton').onclick = () => { if (!requireRunningMatch() && !validFinalScore(liveFor(activeMatch()), matchRules(activeMatch()))) return; undo(); };
    $$('[data-server-player]').forEach(button => button.onclick = () => transact(`Server changed to ${button.textContent}`, live => live.serverPlayer = Number(button.dataset.serverPlayer)));
    $$('[data-base-player]').forEach(button => button.onclick = () => transact(`Receiving base changed to ${button.textContent}`, live => live.basePlayer = Number(button.dataset.basePlayer)));
    $$('[data-timeout]').forEach(button => button.onclick = () => showInterruptionConfirmation(`timeout-${button.dataset.timeout}`, `${teamName(button.dataset.timeout)} timeout`));
    $('#medicalButton').onclick = () => showInterruptionConfirmation('medical', 'Medical timeout'); $('#technicalTimeoutButton').onclick = () => showInterruptionConfirmation('technical', 'Technical timeout'); $('#refereeTimeoutButton').onclick = () => showInterruptionConfirmation('referee', 'Referee timeout'); $('#equipmentTimeoutButton').onclick = () => showInterruptionConfirmation('equipment', 'Equipment timeout'); if ($('#endOfficialInterruption')) $('#endOfficialInterruption').onclick = () => endOfficialInterruption(false); $('#finishButton').onclick = showConfirmation;
    if ($('#resumeAfterInterruption')) $('#resumeAfterInterruption').onclick=()=>{liveFor(activeMatch()).lastInterruption=null;toggleTimer();}; if ($('#confirmEndsChanged')) $('#confirmEndsChanged').onclick = confirmEndsChanged; if ($('#confirmWinningScore')) $('#confirmWinningScore').onclick = () => { $('.referee-flow-overlay')?.remove(); launchConfetti(); showConfirmation(); }; if ($('#undoWinningPoint')) $('#undoWinningPoint').onclick = undo;
  }
  function launchConfetti() { const layer = document.createElement('div'); layer.className = 'confetti-layer'; layer.innerHTML = Array.from({ length: 70 }, (_, index) => `<i style="--x:${Math.random() * 100};--delay:${Math.random() * .5}s;--duration:${1.8 + Math.random() * 1.6}s;--spin:${Math.random() * 720}deg;--color:${['#b6ff3c','#4fb6ff','#ffc24b','#ffffff','#ef5b4c'][index % 5]}"></i>`).join(''); document.body.append(layer); setTimeout(() => layer.remove(), 3800); }
  function confirmEndsChanged() { const live = liveFor(activeMatch()); live.endsChanged = true; addLog(live, `Change of ends confirmed at ${endsChangeScore(matchRules(activeMatch()))}`); save(); renderScorekeeper(); toast('Change of ends confirmed. Continue play.'); }
  function showInterruptionConfirmation(type, label) { if (!scoringIsOpen()) return toast('Start or resume the match timer before logging a score.'); const teamTimeout = type === 'timeout-a' || type === 'timeout-b', rules = matchRules(activeMatch()), sheet = $('#interruptionSheet'); if (teamTimeout && rules.mode === 'preliminary') return toast('Team timeouts are not allowed during preliminary matches.'); const side = teamTimeout ? type.slice(-1) : ''; if (teamTimeout && liveFor(activeMatch()).timeouts[side] >= 1) return toast('That club has already used its one timeout.'); sheet.hidden = false; sheet.innerHTML = `<div class="confirm-backdrop"><section class="confirm-card interruption-confirm"><button class="confirm-close" id="closeInterruption">×</button><span class="eyebrow">Confirm interruption</span><h2>${esc(label)}</h2><p>${teamTimeout ? 'This is the club’s single 60-second timeout.' : type === 'medical' ? 'Medical timeout has a five-minute maximum and ends automatically.' : 'The interruption timer starts immediately.'} The match timer pauses automatically.</p><button class="finish-match" id="startInterruption">Confirm and start timer</button></section></div>`; $('#closeInterruption').onclick = () => sheet.hidden = true; $('#startInterruption').onclick = () => { const live = liveFor(activeMatch()); if (teamTimeout) live.timeouts[side]++; else if (type === 'medical') live.medical++; else if (type === 'technical') live.technicalTimeouts++; else if (type === 'referee') live.refereeTimeouts++; else live.equipmentTimeouts++; const resumeMatchOnEnd = Boolean(live.running); if (resumeMatchOnEnd) { live.elapsed = elapsed(live); live.running = false; live.startedAt = null; } live.interruption = { type, label, active: true, running: true, startedAt: Date.now(), elapsed: 0, resumeMatchOnEnd }; addLog(live, `${label} started; match timer ${resumeMatchOnEnd ? 'paused automatically' : 'was already paused'}`); save(); renderScorekeeper(); } }
  function endOfficialInterruption(expired=false) { const match = activeMatch(), live = liveFor(match); if (!live.interruption?.active) return; const ended={...live.interruption},resumeMatch = Boolean(ended.resumeMatchOnEnd) && !live.complete && !state.scores[match.id]; ended.elapsed = elapsed(ended); live.interruption={...ended,running:false,active:false,resumeMatchOnEnd:false}; live.lastInterruption=expired&&!resumeMatch?{label:ended.label,expired:true}:null; if (resumeMatch) { live.running = true; live.startedAt = Date.now(); } addLog(live, `${ended.label} ended after ${clock(ended.elapsed)}; match timer ${resumeMatch ? 'resumed automatically' : 'is ready to resume'}`); save(); renderScorekeeper(); toast(`${ended.label} time is up. ${resumeMatch ? 'Match resumed.' : 'Tap Resume match.'}`); }
  function toggleTimer() { const match = activeMatch(), live = match && liveFor(match); if (!live || state.scores?.[match.id] || live.interruption?.active) return; if (live.running) { live.elapsed = elapsed(live); live.running = false; live.startedAt = null; addLog(live, 'Match timer paused'); } else { live.running = true; live.startedAt = Date.now(); addLog(live, live.elapsed ? 'Match timer resumed' : 'Match timer started'); } save(); renderScorekeeper(); }
  function updateClock() { if (!activeId) return; state = load(); const match = activeMatch(), live = match ? liveFor(match) : null, el = $('#officialClock'), startEl = $('#startMatchClock'), interruptionEl = $('#officialInterruptionClock'); if (match && el) el.textContent = clock(elapsed(live)); if (match && startEl) startEl.textContent = clock(elapsed(live)); if (live?.interruption?.active && interruptionEl) { const interruptionSeconds = elapsed(live.interruption); interruptionEl.textContent = clock(interruptionSeconds); if ((String(live.interruption.type).startsWith('timeout-') && interruptionSeconds >= 60) || (live.interruption.type === 'medical' && interruptionSeconds >= 300)) endOfficialInterruption(true); } }
  function undo() { const live = liveFor(activeMatch()), prior = live.history.pop(); if (!prior) return toast('Nothing to undo.'); Object.assign(live, prior); addLog(live, 'Previous action undone'); save(); renderScorekeeper(); }
  function setupCanvas(canvas) { const ctx = canvas.getContext('2d'); ctx.lineWidth = 2; ctx.lineCap = 'round'; let drawing = false; const position = event => { const rect = canvas.getBoundingClientRect(); return { x: (event.clientX - rect.left) * canvas.width / rect.width, y: (event.clientY - rect.top) * canvas.height / rect.height }; }; canvas.onpointerdown = event => { drawing = true; const p = position(event); ctx.beginPath(); ctx.moveTo(p.x, p.y); }; canvas.onpointermove = event => { if (!drawing) return; const p = position(event); ctx.lineTo(p.x, p.y); ctx.stroke(); }; canvas.onpointerup = canvas.onpointerleave = () => drawing = false; }
  function showConfirmation() {
    const match = activeMatch(), live = liveFor(match), rules = matchRules(match), earlyTimedResult=rules.mode==='preliminary'&&Number(live.a)!==Number(live.b), winnerReady = validFinalScore(live, rules) && Number(live.a) !== Number(live.b); if (!scoringIsOpen() && !winnerReady) return toast('Start or resume the match timer before logging a result.'); if (!validFinalScore(live, rules)&&!earlyTimedResult) return toast(rules.mode === 'preliminary' ? 'A preliminary match may end on time at its current non-tied score.' : 'First to 11, win by 2, with a 15-point maximum cap.'); if (live.running) toggleTimer();
    const sheet = $('#confirmationSheet'); sheet.hidden = false; sheet.innerHTML = `<div class="confirm-backdrop"><section class="confirm-card"><button class="confirm-close" id="closeConfirmation">×</button><span class="eyebrow">Player confirmation</span><h2>Final score ${live.a}-${live.b}</h2><p>Both pairs review the result, then sign below.</p><div class="signature-grid"><div class="signature-box"><label>${esc(teamName('a'))} pair signature</label><canvas width="320" height="120"></canvas><button data-clear-signature>Clear</button></div><div class="signature-box"><label>${esc(teamName('b'))} pair signature</label><canvas width="320" height="120"></canvas><button data-clear-signature>Clear</button></div></div><button class="finish-match" id="submitResult">Submit confirmed result</button></section></div>`;
    $$('canvas', sheet).forEach(setupCanvas); $$('[data-clear-signature]', sheet).forEach(button => button.onclick = () => { const canvas = $('canvas', button.parentElement); canvas.getContext('2d').clearRect(0, 0, canvas.width, canvas.height); }); $('#closeConfirmation').onclick = () => sheet.hidden = true; $('#submitResult').onclick = submitResult;
  }
  function hasInk(canvas) { return canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data.some(value => value); }
  function submitResult() {
    const match = activeMatch(), live = liveFor(match), canvases = $$('#confirmationSheet canvas'); if (!canvases.every(hasInk)) return toast('Both pairs must sign first.'); const prior = state.scores[match.id];
    const rules = matchRules(match), regulation = Math.max(Number(live.a), Number(live.b)) >= rules.target; state.scores[match.id] = { a: live.a, b: live.b, resultType: regulation ? 'finishing-score' : 'timer-expired', completedAt: prior?.completedAt || new Date().toISOString(), confirmation: { referee: email, submittedAt: new Date().toISOString(), aSignature: canvases[0].toDataURL('image/png'), bSignature: canvases[1].toDataURL('image/png') } }; live.complete = true; live.running = false; live.startedAt = null; addLog(live, `Final result submitted: ${live.a}-${live.b}`); state.scoreAudit ||= []; state.scoreAudit.push({ matchId: match.id, previous: prior || null, revised: state.scores[match.id], source: `referee:${email}`, revisedAt: new Date().toISOString() }); save(); $('#confirmationSheet').hidden = true; renderScorekeeper(); toast('Confirmed result sent to Match Control.');
  }
  $('#officialLoginForm').onsubmit = async event => { event.preventDefault(); const button = $('#officialLogin'); button.disabled = true; button.textContent = 'Signing in…'; $('#loginError').textContent = ''; try { await login($('#officialEmail').value.trim().toLowerCase(), $('#officialPassword').value); } catch (error) { $('#loginError').textContent = error.code === 'auth/invalid-credential' ? 'The email or password is incorrect.' : error.code === 'auth/too-many-requests' ? 'Too many attempts. Wait a moment and try again.' : 'Sign-in failed. Check your connection and try again.'; } finally { button.disabled = false; button.textContent = 'Sign in to referee assignments'; } };
  watchAuth(async user => {
    cloudUser = user;
    $('#refereeAccount').hidden = !user; $('#refereeLogin').hidden = Boolean(user); $('#assignmentSummary').hidden = !user;
    if (!user) { email = ''; $('#matchList').innerHTML = ''; $('#loginError').textContent = ''; return; }
    email = user.email.toLowerCase();
    $('#officialEmail').value = email;
    $('#refereeAccountEmail').textContent = email; $('#officialLogout').onclick = logout;
    $('#matchList').innerHTML = '<section class="field-card access-warning"><h2>Verifying referee access</h2><p>Checking this OCPC account and loading the tournament court board…</p></section>';
    let profile = null; try { profile = await getCurrentProfile(user); } catch (_) {}
    const roles = new Set([...(Array.isArray(profile?.roles) ? profile.roles : []), ...(profile?.role ? [profile.role] : [])]), superAdmin = ['ocpc.pickleball@gmail.com','jamescastillo37@gmail.com'].includes(email);
    if (!superAdmin && !roles.has('admin') && !roles.has('owner') && !roles.has('tournament_admin') && !roles.has('match_control') && !roles.has('tournament_referee')) { $('#matchList').innerHTML = `<section class="field-card access-warning"><h2>Waiting for referee access</h2><p>Signed in as <b>${esc(email)}</b>. This page will open automatically as soon as Match Control grants Referee access.</p></section>`; $('#assignmentSummary').hidden = true; const stop=watchMembership(user.uid,membership=>{const granted=new Set(Array.isArray(membership?.roles)?membership.roles:membership?.role?[membership.role]:[]);if(granted.has('tournament_referee')||granted.has('match_control')||granted.has('tournament_admin')||granted.has('owner')){stop();location.reload();}},()=>{}); return; }
    watchRefereeBoard(incoming => {
      if (!incoming) { $('#matchList').innerHTML = '<section class="field-card access-warning"><h2>Referee board is preparing</h2><p>Ask Match Control to open the tournament dashboard once to publish the referee court board.</p></section>'; return; }
      const local = load(), matchLive = {}, matchScores = { ...(incoming.scores || {}) };
      if (latestMatchDocsReady) {
        latestMatchDocs.forEach((item, matchId) => {
          if (item.live) matchLive[matchId] = item.live;
          if (Object.prototype.hasOwnProperty.call(item, 'score')) { if (item.score) matchScores[matchId] = item.score; else delete matchScores[matchId]; }
        });
      } else {
        Object.assign(matchLive, local?.liveScoring || {}); Object.assign(matchScores, local?.scores || {});
      }
      pendingMatchWrites.forEach((_, matchId) => { if (local?.liveScoring?.[matchId]) matchLive[matchId] = local.liveScoring[matchId]; if (local?.scores?.[matchId]) matchScores[matchId] = local.scores[matchId]; });
      state = { ...incoming, scores: matchScores, liveScoring: matchLive, checkins:local?.checkins || {} };
      localStorage.setItem(config.storageKey, JSON.stringify(state)); if (pendingPromotionId && activeCourtFor(pendingPromotionId)) enterScorekeeper(pendingPromotionId); else activeId ? renderScorekeeper() : renderAssignments();
    }, () => { $('#matchList').innerHTML = '<section class="field-card access-warning"><h2>Referee access not granted</h2><p>You are signed in successfully, but this OCPC account does not have the Referee staff role.</p></section>'; $('#assignmentSummary').hidden = true; });
    watchMatches(items => {
      state ||= load(); if (!state) return;
      latestMatchDocsReady = true; latestMatchDocs.clear(); items.forEach(item => latestMatchDocs.set(item.id, item));
      const localLive = state.liveScoring || {}, localScores = state.scores || {}, nextLive = {}, nextScores = { ...localScores };
      items.forEach(item => {
        if (pendingMatchWrites.has(item.id)) {
          if (localLive[item.id]) nextLive[item.id] = localLive[item.id];
          return;
        }
        if (Object.prototype.hasOwnProperty.call(item, 'live') && item.live) nextLive[item.id] = item.live;
        if (Object.prototype.hasOwnProperty.call(item, 'score')) { if (item.score) nextScores[item.id] = item.score; else delete nextScores[item.id]; }
      });
      pendingMatchWrites.forEach((_, matchId) => { if (localLive[matchId]) nextLive[matchId] = localLive[matchId]; });
      state.liveScoring = nextLive; state.scores = nextScores;
      localStorage.setItem(config.storageKey, JSON.stringify(state));
      activeId ? renderScorekeeper() : renderAssignments();
    }, () => toast('Live match sync unavailable.'));
    watchCheckins(items => { if (!state) return; state.checkins = Object.fromEntries(items.map(item => [item.id, item])); localStorage.setItem(config.storageKey, JSON.stringify(state)); activeId ? renderScorekeeper() : renderAssignments(); }, () => toast('Player photos unavailable.'));
  });
  window.addEventListener('storage', () => { if (!email) return; activeId ? renderScorekeeper() : renderAssignments(); });
})();
