const revision = new URL(import.meta.url).searchParams.get('v') || 'dev';
const { watchAuth, login, logout, getCurrentProfile, watchRefereeBoard, watchMatches, watchCheckins, publishMatch } = await import(`../firebase-sync.js?v=${encodeURIComponent(revision)}`);

(() => {
  'use strict';
  const config = window.TOURNAMENT_CONFIG;
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
  let state, email = '', activeId = null, tick, cloudUser = null;

  function load() { try { return JSON.parse(localStorage.getItem(config.storageKey)); } catch (_) { return null; } }
  function save() { state.updatedAt = new Date().toISOString(); localStorage.setItem(config.storageKey, JSON.stringify(state)); if (cloudUser && activeId) publishMatch(activeId, state.liveScoring?.[activeId], state.scores?.[activeId] || null).catch(() => toast('Saved locally. Cloud sync failed.')); }
  function players(category, code) { const p = state.pairs[`${category}|${code}`] || {}; return [p.player1 || `${code} Player 1`, p.player2 || `${code} Player 2`]; }
  function playerPhoto(category, code, clubId, index) { return Object.values(state.checkins || {}).find(item => item.category === category && item.pair === code && item.club === clubId && Number(item.playerIndex) === index)?.photoThumb || ''; }
  function names(category, code) { return players(category, code).join(' / '); }
  function prefix(category) { return category === 'Novice' ? 'NOV' : category === 'Low Intermediate' ? 'LOW' : 'HIGH'; }
  function toast(message) { const el = $('#officialToast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 1800); }
  function clock(seconds) { return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; }
  function elapsed(live) { return (live.elapsed || 0) + (live.running && live.startedAt ? Math.max(0, Math.floor((Date.now() - live.startedAt) / 1000)) : 0); }
  function defaultLive() { return { a: 0, b: 0, serving: 'a', server: 2, serverPlayer: 0, basePlayer: 0, timeouts: { a: 0, b: 0 }, medical: 0, technicalTimeouts: 0, refereeTimeouts: 0, equipmentTimeouts: 0, interruption: null, endsChanged: false, running: false, startedAt: null, elapsed: 0, complete: false, pregame: { complete: false, caller: 'a', call: 'heads', result: '', winner: '', firstChoice: 'serve', courtEnd: 'North / Court A', otherChoice: 'receive', finalChoice: 'serve' }, log: [], history: [] }; }
  function liveFor(match) { state.liveScoring ||= {}; return state.liveScoring[match.id] ||= defaultLive(); }
  function addLog(live, text) { live.log.unshift({ at: new Date().toISOString(), text }); live.log = live.log.slice(0, 30); }
  function activeMatch() { return state.matches.find(match => match.id === activeId); }
  function matchRules(match) { return state.matchSettings?.[match.id] || { mode: 'round-robin', label: 'Round Robin', target: 11, suddenDeathAt: 10, timer: true }; }
  function validFinalScore(live, rules) { const high = Math.max(Number(live.a), Number(live.b)), low = Math.min(Number(live.a), Number(live.b)); return high >= rules.target && high <= Math.max(rules.target, rules.suddenDeathAt) && high - low >= 2 || high === rules.suddenDeathAt + 1 && low === rules.suddenDeathAt; }
  function endsChangeScore(rules) { return rules.target === 11 ? 6 : rules.target === 15 ? 8 : Math.ceil(rules.target / 2); }

  function renderAssignments() {
    state = load(); if (!state) return;
    const matches = state.matches.filter(match => state.refereeAssignments?.[match.id] === email);
    const statusFor = match => state.scores[match.id] ? 'complete' : state.liveScoring?.[match.id] ? 'live' : 'ready';
    const statusOrder = { live: 0, ready: 1, complete: 2 };
    const ordered = [...matches].sort((a, b) => statusOrder[statusFor(a)] - statusOrder[statusFor(b)] || String(a.time).localeCompare(String(b.time)));
    const counts = ordered.reduce((all, match) => { all[statusFor(match)]++; return all; }, { live: 0, ready: 0, complete: 0 });
    $('#assignmentSummary').hidden = false; $('#assignmentSummary').innerHTML = `<span><b>${counts.live}</b> Live</span><span><b>${counts.ready}</b> Upcoming</span><span><b>${counts.complete}</b> Complete</span>`;
    const courtCards = Array.from({ length: config.event.courts }, (_, index) => { const courtNo = index + 1, court = state.courts?.[courtNo] || {}, match = state.matches.find(item => item.id === court.matchId), assigned = match && state.refereeAssignments?.[match.id] === email; if (!match) return `<article class="referee-court-card vacant"><header><b>Court ${courtNo}</b><span>Vacant</span></header><div><strong>Available court</strong><small>Waiting for Match Control</small></div></article>`; const live = state.liveScoring?.[match.id], score = state.scores?.[match.id] || live, status = state.scores?.[match.id] ? 'Final' : live?.running ? 'Live' : live ? 'Ready' : 'Scheduled'; return `<article class="referee-court-card ${assigned ? 'assigned' : ''}"><header><b>Court ${courtNo}</b><span>${assigned ? 'Assigned to you' : status}</span></header><div><small>${esc(match.category)} · ${esc(match.id)}</small><strong>${esc(names(match.category, match.a))}</strong><em>vs</em><strong>${esc(names(match.category, match.b))}</strong>${score ? `<b class="referee-court-score">${score.a || 0}–${score.b || 0}</b>` : ''}${assigned ? `<button class="action" data-open-match="${match.id}">${live ? 'Open live scorekeeper' : 'Begin officiating'}</button>` : '<button class="action alt" disabled>View only</button>'}</div></article>`; }).join('');
    const activeIds = new Set(Object.values(state.courts || {}).map(court => court.matchId).filter(Boolean));
    const assignedList = ordered.filter(match => !activeIds.has(match.id)).map(match => {
      const live = state.liveScoring?.[match.id], final = state.scores[match.id];
      const status = final ? `Final ${final.a}-${final.b}` : live ? `Live ${live.a}-${live.b}` : 'Ready';
      return `<article class="official-match assignment-card assignment-${statusFor(match)}"><div><div class="match-meta"><span>${esc(match.category)}</span><b>${match.id}</b><span>${esc(match.time || `Wave ${match.wave}`)} · Court ${match.court || 'TBA'}</span></div><div class="match-pairs"><div><strong>${prefix(match.category)}-${match.a}</strong><small>${esc(names(match.category, match.a))}</small></div><b>VS</b><div><strong>${prefix(match.category)}-${match.b}</strong><small>${esc(names(match.category, match.b))}</small></div></div></div><div class="assignment-action"><span class="live-status">${status}</span><button class="action" data-open-match="${match.id}">${final ? 'Review match' : live ? 'Resume scorekeeper' : 'Open scorekeeper'}</button></div></article>`;
    }).join('');
    $('#matchList').innerHTML = `<section class="referee-court-board"><div class="referee-board-title"><span class="eyebrow">Live venue</span><h2>Courts now</h2><p>All courts are visible. Scoring opens only on matches assigned to your exact account email.</p></div><div class="referee-court-grid">${courtCards}</div></section><section class="referee-upcoming"><h2>Your next assignments</h2>${assignedList || '<div class="field-card"><p>No additional matches are assigned yet.</p></div>'}</section>`;
    $$('[data-open-match]').forEach(button => button.onclick = () => openMatch(button.dataset.openMatch));
  }

  function openMatch(id) { activeId = id; $('#assignmentView').hidden = true; $('#scorekeeperView').hidden = false; renderScorekeeper(); clearInterval(tick); tick = setInterval(updateClock, 1000); }
  function closeMatch() { activeId = null; clearInterval(tick); $('#scorekeeperView').hidden = true; $('#assignmentView').hidden = false; renderAssignments(); }
  function teamPanel(side, club, code, playerNames, live, category, rules) {
    const serving = live.serving === side;
    const clubId = side === 'a' ? 'ocpc' : 'rebels';
    return `<article class="score-team ${serving ? 'serving' : ''}"><div class="team-heading"><span>${club}</span><b>${prefix(category)}-${code}</b></div><strong class="giant-score">${live[side]}</strong><div class="player-tags">${playerNames.map((name,index) => { const image = playerPhoto(category,code,clubId,index); return `<span class="${serving && live.serverPlayer === index ? 'server' : ''}">${image ? `<img src="${image}" alt="">` : '<i class="photo-placeholder"></i>'}<b>${esc(name)}</b></span>`; }).join('')}</div><button class="point-button" data-point="${side}" ${(rules.scoring === 'rally' || serving) && !live.complete ? '' : 'disabled'}>+ Point</button></article>`;
  }
  function teamName(side) { return side === 'a' ? 'OCPC' : 'Rally Rebels'; }
  function renderPregame(match, live) {
    const pregame = live.pregame ||= defaultLive().pregame, loser = pregame.winner === 'a' ? 'b' : 'a';
    const tossOverlay = !pregame.winner ? `<div class="coin-toss-overlay"><section><span class="eyebrow">Official pre-match toss</span><h2>Coin Toss</h2><div class="peso-coin ${pregame.result || 'obverse'} ${pregame.result ? 'flipped' : ''}"></div>${pregame.result ? `<p>The coin has landed. Record the club that won the physical toss.</p><div class="toss-winner-buttons"><button data-toss-winner="a">OCPC won</button><button data-toss-winner="b">Rally Rebels won</button></div>` : `<p>No heads-or-tails caller is stored. Toss the coin, then tap the actual winner.</p><button class="toss-main-button" id="flipCoin">Toss coin</button>`}<button class="toss-cancel" id="backToMatchesOverlay">Back to assignments</button></section></div>` : '';
    $('#scorekeeperView').innerHTML = `<div class="pregame-shell"><button class="back-button pregame-back" id="backToMatches">← Assigned matches</button><span class="eyebrow">${match.id} · ${esc(match.category)}</span><h1>Pre-match setup</h1><p class="sub">The toss winner records a first choice of serve, receive, starting end, or defer.</p>
      ${pregame.winner ? `<section class="choice-card"><span class="choice-winner">${teamName(pregame.winner)} won the toss</span><h2>Record the choices</h2><label>Winner's first choice<select id="firstChoice"><option value="serve" ${pregame.firstChoice === 'serve' ? 'selected' : ''}>Serve first</option><option value="receive" ${pregame.firstChoice === 'receive' ? 'selected' : ''}>Receive first</option><option value="end" ${pregame.firstChoice === 'end' ? 'selected' : ''}>Choose starting end</option><option value="defer" ${pregame.firstChoice === 'defer' ? 'selected' : ''}>Defer first choice</option></select></label>${choiceFields(pregame, loser)}<button class="finish-match" id="confirmPregame">Confirm setup and open scorekeeper</button></section>` : ''}
      <aside class="rules-note"><b>Event scoring notice</b><p>Side-out scoring to 11 is standard. This event's sudden-death point at 10-10 and 15-minute operational target are tournament-specific modifications.</p></aside></div>${tossOverlay}`;
    $('#backToMatches').onclick = closeMatch; if ($('#backToMatchesOverlay')) $('#backToMatchesOverlay').onclick = closeMatch; if ($('#flipCoin')) $('#flipCoin').onclick = flipCoin; $$('[data-toss-winner]').forEach(button => button.onclick = () => { pregame.winner = button.dataset.tossWinner; addLog(live, `${teamName(pregame.winner)} recorded as toss winner`); save(); renderPregame(match, live); });
    if (pregame.winner) { $('#firstChoice').onchange = event => { pregame.firstChoice = event.target.value; save(); renderPregame(match, live); }; $$('[data-pregame-field]').forEach(input => input.onchange = () => { pregame[input.dataset.pregameField] = input.value; save(); if (input.dataset.rerender) renderPregame(match, live); }); $('#confirmPregame').onclick = confirmPregame; }
  }
  function choiceFields(pregame, loser) {
    const endField = `<label>Starting court end<select data-pregame-field="courtEnd"><option ${pregame.courtEnd === 'North / Court A' ? 'selected' : ''}>North / Court A</option><option ${pregame.courtEnd === 'South / Court B' ? 'selected' : ''}>South / Court B</option></select></label>`;
    if (pregame.firstChoice === 'serve' || pregame.firstChoice === 'receive') return `<p>${teamName(loser)} receives the remaining choice of starting end.</p>${endField}`;
    if (pregame.firstChoice === 'end') return `${endField}<label>${teamName(loser)} chooses<select data-pregame-field="otherChoice"><option value="serve" ${pregame.otherChoice === 'serve' ? 'selected' : ''}>Serve first</option><option value="receive" ${pregame.otherChoice === 'receive' ? 'selected' : ''}>Receive first</option></select></label>`;
    return `<label>${teamName(loser)} receives first choice<select data-pregame-field="otherChoice" data-rerender="true"><option value="serve" ${pregame.otherChoice === 'serve' ? 'selected' : ''}>Serve first</option><option value="receive" ${pregame.otherChoice === 'receive' ? 'selected' : ''}>Receive first</option><option value="end" ${pregame.otherChoice === 'end' ? 'selected' : ''}>Choose starting end</option></select></label>${endField}${pregame.otherChoice === 'end' ? `<label>${teamName(pregame.winner)} then chooses<select data-pregame-field="finalChoice"><option value="serve" ${pregame.finalChoice === 'serve' ? 'selected' : ''}>Serve first</option><option value="receive" ${pregame.finalChoice === 'receive' ? 'selected' : ''}>Receive first</option></select></label>` : ''}`;
  }
  function flipCoin() { const live = liveFor(activeMatch()), pregame = live.pregame; pregame.result = crypto.getRandomValues(new Uint8Array(1))[0] % 2 ? 'obverse' : 'reverse'; pregame.winner = ''; addLog(live, 'Coin tossed; awaiting recorded winner'); save(); renderPregame(activeMatch(), live); }
  function confirmPregame() {
    const live = liveFor(activeMatch()), pregame = live.pregame, loser = pregame.winner === 'a' ? 'b' : 'a';
    if (pregame.firstChoice === 'serve') live.serving = pregame.winner;
    else if (pregame.firstChoice === 'receive') live.serving = loser;
    else if (pregame.firstChoice === 'end') live.serving = pregame.otherChoice === 'serve' ? loser : pregame.winner;
    else if (pregame.otherChoice === 'serve') live.serving = loser;
    else if (pregame.otherChoice === 'receive') live.serving = pregame.winner;
    else live.serving = pregame.finalChoice === 'serve' ? pregame.winner : loser;
    live.server = 2; live.serverPlayer = 0; live.basePlayer = 0; pregame.complete = true;
    addLog(live, `Pre-match choices confirmed. ${teamName(live.serving)} serves first; opening call 0-0-2.`); save(); renderScorekeeper();
  }
  function renderScorekeeper() {
    state = load(); const match = activeMatch(); if (!match) return closeMatch();
    const live = liveFor(match);
    if (!live.pregame?.complete) return renderPregame(match, live);
    const aPlayers = players(match.category, match.a), bPlayers = players(match.category, match.b), servingPlayers = live.serving === 'a' ? aPlayers : bPlayers, receivingPlayers = live.serving === 'a' ? bPlayers : aPlayers, final = state.scores[match.id], rules = matchRules(match), changeAt = endsChangeScore(rules), endsDue = !final && !live.endsChanged && Math.max(live.a, live.b) >= changeAt, winnerSide = validFinalScore(live, rules) ? (Number(live.a) > Number(live.b) ? 'a' : 'b') : '', winnerClub = winnerSide === 'a' ? 'OCPC' : 'Rally Rebels', winnerPair = winnerSide === 'a' ? names(match.category, match.a) : names(match.category, match.b);
    const flowOverlay = endsDue ? `<div class="referee-flow-overlay change-ends"><section><span>CHANGE ENDS</span><h2>Switch court ends</h2><strong>${changeAt}-point midpoint reached</strong><p>Pause play and confirm that both pairs have changed ends before the next serve.</p><button id="confirmEndsChanged">Players changed ends · Continue play</button></section></div>` : winnerSide && !final ? `<div class="referee-flow-overlay winner"><section><span>MATCH COMPLETE</span><h2>${esc(winnerClub)} wins</h2><strong>${live.a}-${live.b}</strong><p>${esc(winnerPair)}</p><button id="confirmWinningScore">Review score and collect signatures</button><button class="flow-secondary" id="undoWinningPoint">Undo last rally</button></section></div>` : '';
    $('#scorekeeperView').innerHTML = `
      <div class="scorekeeper-top"><button class="back-button" id="backToMatches">← Matches</button><div><span>${match.id} · ${esc(match.category)} · ${esc(rules.label)}</span><b>${final ? 'Match complete' : 'Live scorekeeper'}</b></div>${rules.timer ? `<button class="timer-button ${live.running ? 'running' : ''}" id="timerToggle"><small>${live.running ? 'Pause match' : elapsed(live) ? 'Resume match' : 'Start match'}</small><strong id="officialClock">${clock(elapsed(live))}</strong></button>` : '<span class="no-official-timer">No timer</span>'}</div>
      <div class="serve-call"><span>Call the score</span><strong>${live.serving === 'a' ? live.a : live.b} - ${live.serving === 'a' ? live.b : live.a} - ${live.server}</strong><small>${esc(servingPlayers[live.serverPlayer])} serving for ${live.serving === 'a' ? 'OCPC' : 'Rally Rebels'}</small></div>${live.interruption?.active ? `<div class="official-interruption ${['medical','technical'].includes(live.interruption.type) ? 'danger' : 'warning'}"><span>${esc(live.interruption.label)}</span><b id="officialInterruptionClock">${clock(elapsed(live.interruption))}</b><button id="endOfficialInterruption">End interruption</button></div>` : ''}
      <div class="live-scoreboard">${teamPanel('a', 'OCPC', match.a, aPlayers, live, match.category, rules)}${teamPanel('b', 'Rally Rebels', match.b, bPlayers, live, match.category, rules)}</div>
      <div class="official-controls"><button class="control-button fault" id="faultButton"><span>✕</span><b>Fault / next server</b><small>${live.server === 1 ? 'Moves to server 2' : 'Awards side out'}</small></button><button class="control-button undo" id="undoButton"><span>↶</span><b>Undo last action</b><small>Correct the previous tap</small></button></div>
      <div class="match-tools"><section><h3>Serving player</h3><div class="segmented"><button data-server-player="0" class="${live.serverPlayer === 0 ? 'active' : ''}">${esc(servingPlayers[0])}</button><button data-server-player="1" class="${live.serverPlayer === 1 ? 'active' : ''}">${esc(servingPlayers[1])}</button></div><h3 style="margin-top:16px">Receiving / base player</h3><div class="segmented"><button data-base-player="0" class="${live.basePlayer === 0 ? 'active' : ''}">${esc(receivingPlayers[0])}</button><button data-base-player="1" class="${live.basePlayer === 1 ? 'active' : ''}">${esc(receivingPlayers[1])}</button></div></section><section><h3>Guarded match interruptions</h3><div class="tool-buttons"><button data-timeout="a" ${rules.mode === 'round-robin' || live.timeouts.a >= 1 ? 'disabled' : ''}>OCPC timeout <b>${rules.mode === 'round-robin' ? 'Not allowed' : `${live.timeouts.a}/1 · 60 sec`}</b></button><button data-timeout="b" ${rules.mode === 'round-robin' || live.timeouts.b >= 1 ? 'disabled' : ''}>Rebels timeout <b>${rules.mode === 'round-robin' ? 'Not allowed' : `${live.timeouts.b}/1 · 60 sec`}</b></button><button id="medicalButton">Medical <b>${live.medical} · 5 min max</b></button><button id="technicalTimeoutButton">Technical <b>${live.technicalTimeouts || 0}</b></button><button id="refereeTimeoutButton">Referee timeout <b>${live.refereeTimeouts || 0}</b></button><button id="equipmentTimeoutButton">Equipment timeout <b>${live.equipmentTimeouts || 0}</b></button></div></section></div>
      <section class="rally-log"><h3>Match log</h3>${live.log.map(item => `<div><time>${new Date(item.at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time><span>${esc(item.text)}</span></div>`).join('')}</section>
      <button class="finish-match" id="finishButton" ${final ? 'disabled' : ''}>${final ? `Submitted final: ${final.a}-${final.b}` : 'Finish match and confirm result'}</button><div id="confirmationSheet" hidden></div><div id="interruptionSheet" hidden></div>${flowOverlay}`;
    bindScorekeeper();
  }

  function snapshot(live) { return { a: live.a, b: live.b, serving: live.serving, server: live.server, serverPlayer: live.serverPlayer, basePlayer: live.basePlayer, timeouts: { ...live.timeouts }, medical: live.medical, technicalTimeouts: live.technicalTimeouts, refereeTimeouts: live.refereeTimeouts, equipmentTimeouts: live.equipmentTimeouts, interruption: live.interruption ? { ...live.interruption } : null, endsChanged: !!live.endsChanged }; }
  function transact(label, change) { const live = liveFor(activeMatch()), rules = matchRules(activeMatch()); live.history.push(snapshot(live)); change(live); addLog(live, label); if (validFinalScore(live, rules) && live.running) { live.elapsed = elapsed(live); live.running = false; live.startedAt = null; addLog(live, 'Finishing score reached; match timer paused'); } save(); renderScorekeeper(); }
  function sideOut(live) { live.serving = live.serving === 'a' ? 'b' : 'a'; live.server = 1; live.serverPlayer = 0; }
  function bindScorekeeper() {
    $('#backToMatches').onclick = closeMatch; if ($('#timerToggle')) $('#timerToggle').onclick = toggleTimer;
    $$('[data-point]').forEach(button => button.onclick = () => transact(`${button.dataset.point === 'a' ? 'OCPC' : 'Rally Rebels'} scored`, live => { const rules = matchRules(activeMatch()), side = button.dataset.point, maximum = Math.max(rules.target, rules.suddenDeathAt + 1); if (rules.scoring === 'rally') { if (live[side] < maximum) live[side]++; if (live.serving !== side) { live.serving = side; live.server = 1; live.serverPlayer = 0; } } else if (live.serving === side && live[side] < maximum) live[side]++; }));
    $('#faultButton').onclick = () => transact('Fault called', live => { if (live.server === 1) { live.server = 2; live.serverPlayer = live.serverPlayer ? 0 : 1; } else sideOut(live); });
    $('#undoButton').onclick = undo;
    $$('[data-server-player]').forEach(button => button.onclick = () => transact(`Server changed to ${button.textContent}`, live => live.serverPlayer = Number(button.dataset.serverPlayer)));
    $$('[data-base-player]').forEach(button => button.onclick = () => transact(`Receiving base changed to ${button.textContent}`, live => live.basePlayer = Number(button.dataset.basePlayer)));
    $$('[data-timeout]').forEach(button => button.onclick = () => showInterruptionConfirmation(`timeout-${button.dataset.timeout}`, `${button.dataset.timeout === 'a' ? 'OCPC' : 'Rally Rebels'} timeout`));
    $('#medicalButton').onclick = () => showInterruptionConfirmation('medical', 'Medical timeout'); $('#technicalTimeoutButton').onclick = () => showInterruptionConfirmation('technical', 'Technical timeout'); $('#refereeTimeoutButton').onclick = () => showInterruptionConfirmation('referee', 'Referee timeout'); $('#equipmentTimeoutButton').onclick = () => showInterruptionConfirmation('equipment', 'Equipment timeout'); if ($('#endOfficialInterruption')) $('#endOfficialInterruption').onclick = endOfficialInterruption; $('#finishButton').onclick = showConfirmation;
    if ($('#confirmEndsChanged')) $('#confirmEndsChanged').onclick = confirmEndsChanged; if ($('#confirmWinningScore')) $('#confirmWinningScore').onclick = () => { $('.referee-flow-overlay')?.remove(); launchConfetti(); showConfirmation(); }; if ($('#undoWinningPoint')) $('#undoWinningPoint').onclick = undo;
  }
  function launchConfetti() { const layer = document.createElement('div'); layer.className = 'confetti-layer'; layer.innerHTML = Array.from({ length: 70 }, (_, index) => `<i style="--x:${Math.random() * 100};--delay:${Math.random() * .5}s;--duration:${1.8 + Math.random() * 1.6}s;--spin:${Math.random() * 720}deg;--color:${['#b6ff3c','#4fb6ff','#ffc24b','#ffffff','#ef5b4c'][index % 5]}"></i>`).join(''); document.body.append(layer); setTimeout(() => layer.remove(), 3800); }
  function confirmEndsChanged() { const live = liveFor(activeMatch()); live.endsChanged = true; addLog(live, `Change of ends confirmed at ${endsChangeScore(matchRules(activeMatch()))}`); save(); renderScorekeeper(); toast('Change of ends confirmed. Continue play.'); }
  function showInterruptionConfirmation(type, label) { const teamTimeout = type === 'timeout-a' || type === 'timeout-b', rules = matchRules(activeMatch()), sheet = $('#interruptionSheet'); if (teamTimeout && rules.mode === 'round-robin') return toast('Team timeouts are not allowed during round robin.'); const side = teamTimeout ? type.slice(-1) : ''; if (teamTimeout && liveFor(activeMatch()).timeouts[side] >= 1) return toast('That club has already used its one timeout.'); sheet.hidden = false; sheet.innerHTML = `<div class="confirm-backdrop"><section class="confirm-card interruption-confirm"><button class="confirm-close" id="closeInterruption">×</button><span class="eyebrow">Confirm interruption</span><h2>${esc(label)}</h2><p>${teamTimeout ? 'This is the club’s single 60-second timeout.' : type === 'medical' ? 'Medical timeout has a five-minute maximum and ends automatically.' : 'The interruption timer starts immediately.'} The match timer pauses automatically.</p><button class="finish-match" id="startInterruption">Confirm and start timer</button></section></div>`; $('#closeInterruption').onclick = () => sheet.hidden = true; $('#startInterruption').onclick = () => { const live = liveFor(activeMatch()); if (teamTimeout) live.timeouts[side]++; else if (type === 'medical') live.medical++; else if (type === 'technical') live.technicalTimeouts++; else if (type === 'referee') live.refereeTimeouts++; else live.equipmentTimeouts++; const resumeMatchOnEnd = Boolean(live.running); if (resumeMatchOnEnd) { live.elapsed = elapsed(live); live.running = false; live.startedAt = null; } live.interruption = { type, label, active: true, running: true, startedAt: Date.now(), elapsed: 0, resumeMatchOnEnd }; addLog(live, `${label} started; match timer ${resumeMatchOnEnd ? 'paused automatically' : 'was already paused'}`); save(); renderScorekeeper(); } }
  function endOfficialInterruption() { const match = activeMatch(), live = liveFor(match); if (!live.interruption?.active) return; const resumeMatch = Boolean(live.interruption.resumeMatchOnEnd) && !live.complete && !state.scores[match.id]; live.interruption.elapsed = elapsed(live.interruption); live.interruption.running = false; live.interruption.active = false; live.interruption.resumeMatchOnEnd = false; if (resumeMatch) { live.running = true; live.startedAt = Date.now(); } addLog(live, `${live.interruption.label} ended after ${clock(live.interruption.elapsed)}; match timer ${resumeMatch ? 'resumed automatically' : 'remained paused'}`); save(); renderScorekeeper(); toast(`Interruption ended. Match timer ${resumeMatch ? 'resumed' : 'remains paused'}.`); }
  function toggleTimer() { const live = liveFor(activeMatch()); if (live.running) { live.elapsed = elapsed(live); live.running = false; live.startedAt = null; addLog(live, 'Match timer paused'); } else { live.running = true; live.startedAt = Date.now(); addLog(live, live.elapsed ? 'Match timer resumed' : 'Match timer started'); } save(); renderScorekeeper(); }
  function updateClock() { if (!activeId) return; state = load(); const match = activeMatch(), live = match ? liveFor(match) : null, el = $('#officialClock'), interruptionEl = $('#officialInterruptionClock'); if (match && el) el.textContent = clock(elapsed(live)); if (live?.interruption?.active && interruptionEl) { const interruptionSeconds = elapsed(live.interruption); interruptionEl.textContent = clock(interruptionSeconds); if ((String(live.interruption.type).startsWith('timeout-') && interruptionSeconds >= 60) || (live.interruption.type === 'medical' && interruptionSeconds >= 300)) endOfficialInterruption(); } }
  function undo() { const live = liveFor(activeMatch()), prior = live.history.pop(); if (!prior) return toast('Nothing to undo.'); Object.assign(live, prior); addLog(live, 'Previous action undone'); save(); renderScorekeeper(); }
  function setupCanvas(canvas) { const ctx = canvas.getContext('2d'); ctx.lineWidth = 2; ctx.lineCap = 'round'; let drawing = false; const position = event => { const rect = canvas.getBoundingClientRect(); return { x: (event.clientX - rect.left) * canvas.width / rect.width, y: (event.clientY - rect.top) * canvas.height / rect.height }; }; canvas.onpointerdown = event => { drawing = true; const p = position(event); ctx.beginPath(); ctx.moveTo(p.x, p.y); }; canvas.onpointermove = event => { if (!drawing) return; const p = position(event); ctx.lineTo(p.x, p.y); ctx.stroke(); }; canvas.onpointerup = canvas.onpointerleave = () => drawing = false; }
  function showConfirmation() {
    const match = activeMatch(), live = liveFor(match), rules = matchRules(match); if (!validFinalScore(live, rules)) return toast(`First to ${rules.target}, win by 2; sudden death at ${rules.suddenDeathAt}-${rules.suddenDeathAt}.`); if (live.running) toggleTimer();
    const sheet = $('#confirmationSheet'); sheet.hidden = false; sheet.innerHTML = `<div class="confirm-backdrop"><section class="confirm-card"><button class="confirm-close" id="closeConfirmation">×</button><span class="eyebrow">Player confirmation</span><h2>Final score ${live.a}-${live.b}</h2><p>Both pairs review the result, then sign below.</p><div class="signature-grid"><div class="signature-box"><label>OCPC pair signature</label><canvas width="320" height="120"></canvas><button data-clear-signature>Clear</button></div><div class="signature-box"><label>Rally Rebels pair signature</label><canvas width="320" height="120"></canvas><button data-clear-signature>Clear</button></div></div><button class="finish-match" id="submitResult">Submit confirmed result</button></section></div>`;
    $$('canvas', sheet).forEach(setupCanvas); $$('[data-clear-signature]', sheet).forEach(button => button.onclick = () => { const canvas = $('canvas', button.parentElement); canvas.getContext('2d').clearRect(0, 0, canvas.width, canvas.height); }); $('#closeConfirmation').onclick = () => sheet.hidden = true; $('#submitResult').onclick = submitResult;
  }
  function hasInk(canvas) { return canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data.some(value => value); }
  function submitResult() {
    const match = activeMatch(), live = liveFor(match), canvases = $$('#confirmationSheet canvas'); if (!canvases.every(hasInk)) return toast('Both pairs must sign first.'); const prior = state.scores[match.id];
    state.scores[match.id] = { a: live.a, b: live.b, completedAt: prior?.completedAt || new Date().toISOString(), confirmation: { referee: email, submittedAt: new Date().toISOString(), ocpcSignature: canvases[0].toDataURL('image/png'), rebelsSignature: canvases[1].toDataURL('image/png') } }; live.complete = true; live.running = false; live.startedAt = null; addLog(live, `Final result submitted: ${live.a}-${live.b}`); state.scoreAudit ||= []; state.scoreAudit.push({ matchId: match.id, previous: prior || null, revised: state.scores[match.id], source: `referee:${email}`, revisedAt: new Date().toISOString() }); save(); $('#confirmationSheet').hidden = true; renderScorekeeper(); toast('Confirmed result sent to Match Control.');
  }
  $('#officialLoginForm').onsubmit = async event => { event.preventDefault(); const button = $('#officialLogin'); button.disabled = true; button.textContent = 'Signing in…'; $('#loginError').textContent = ''; try { await login($('#officialEmail').value.trim().toLowerCase(), $('#officialPassword').value); } catch (error) { $('#loginError').textContent = error.code === 'auth/invalid-credential' ? 'The email or password is incorrect.' : error.code === 'auth/too-many-requests' ? 'Too many attempts. Wait a moment and try again.' : 'Sign-in failed. Check your connection and try again.'; } finally { button.disabled = false; button.textContent = 'Sign in to referee assignments'; } };
  watchAuth(async user => {
    cloudUser = user;
    $('#refereeAccount').hidden = !user; $('#refereeLogin').hidden = Boolean(user); $('#assignmentSummary').hidden = !user;
    if (!user) { email = ''; $('#matchList').innerHTML = ''; $('#loginError').textContent = ''; return; }
    email = user.email.toLowerCase();
    $('#officialEmail').value = email;
    $('#refereeAccountEmail').textContent = email; $('#officialLogout').onclick = logout;
    $('#matchList').innerHTML = '<section class="field-card access-warning"><h2>Verifying referee access</h2><p>Checking this OCPC account and loading the tournament court board…</p></section>';
    let profile = null; try { profile = await getCurrentProfile(user); } catch (_) {}
    const roles = new Set([...(Array.isArray(profile?.roles) ? profile.roles : []), ...(profile?.role ? [profile.role] : [])]), superAdmin = ['ocpc.pickleball@gmail.com','jamescastillo37@gmail.com'].includes(email);
    if (!superAdmin && !roles.has('admin') && !roles.has('tournament_admin') && !roles.has('match_control') && !roles.has('court_manager') && !roles.has('tournament_referee')) { $('#matchList').innerHTML = `<section class="field-card access-warning"><h2>Referee access is not attached to this account</h2><p>Signed in as <b>${esc(email)}</b>. Match Control must grant Referee access to this exact email, then reopen this page.</p></section>`; $('#assignmentSummary').hidden = true; return; }
    watchRefereeBoard(incoming => { if (!incoming) { $('#matchList').innerHTML = '<section class="field-card access-warning"><h2>Referee board is preparing</h2><p>Ask Match Control to open the tournament dashboard once to publish the referee court board.</p></section>'; return; } const local = load(); state = { ...incoming, liveScoring: local?.liveScoring || {}, checkins:local?.checkins || {} }; localStorage.setItem(config.storageKey, JSON.stringify(state)); activeId ? renderScorekeeper() : renderAssignments(); }, () => { $('#matchList').innerHTML = '<section class="field-card access-warning"><h2>Referee access not granted</h2><p>You are signed in successfully, but this OCPC account does not have the Referee staff role.</p></section>'; $('#assignmentSummary').hidden = true; });
    watchMatches(items => { state ||= load(); if (!state) return; state.liveScoring = {}; state.scores ||= {}; items.forEach(item => { if (item.live) state.liveScoring[item.id] = item.live; if (item.score) state.scores[item.id] = item.score; }); localStorage.setItem(config.storageKey, JSON.stringify(state)); activeId ? renderScorekeeper() : renderAssignments(); }, () => toast('Live match sync unavailable.'));
    watchCheckins(items => { if (!state) return; state.checkins = Object.fromEntries(items.map(item => [item.id, item])); localStorage.setItem(config.storageKey, JSON.stringify(state)); activeId ? renderScorekeeper() : renderAssignments(); }, () => toast('Player photos unavailable.'));
  });
  window.addEventListener('storage', () => { if (!email) return; activeId ? renderScorekeeper() : renderAssignments(); });
})();
