const revision = new URL(import.meta.url).searchParams.get('v') || 'dev';
const { watchAuth, login, logout, watchControl, watchRegistrations, watchCheckins, publishControl, publishCheckin, deleteCheckin } = await import(`../firebase-sync.js?v=${encodeURIComponent(revision)}`);

(() => {
  const config = window.TOURNAMENT_CONFIG, $ = selector => document.querySelector(selector), esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  let state = null, registrations = [], selected = null, photoThumb = '', stream = null;
  const toast = message => { const el = $('#officialToast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 1800); };
  function playerRecords() { return registrations.filter(reg => reg.status === 'confirmed').flatMap(reg => (reg.players || []).map((player, index) => ({ id: `${reg.id}:${index}`, registrationId: reg.id, playerIndex: index, fullName: player.fullName, category: reg.category, club: reg.club, clubName: reg.clubName, pairCode: reg.pairCode, dupr: player.dupr || '' }))).sort((a,b) => a.fullName.localeCompare(b.fullName)); }
  function fillPlayers() { const current = $('#registeredPlayer').value; $('#registeredPlayer').innerHTML = '<option value="">Select player</option>' + playerRecords().map(player => `<option value="${player.id}">${esc(player.fullName)} · ${esc(player.category)} · ${esc(player.pairCode)}</option>`).join(''); $('#registeredPlayer').value = current; }
  function choosePlayer() { selected = playerRecords().find(player => player.id === $('#registeredPlayer').value) || null; const prior = selected && state?.checkins?.[selected.id]; photoThumb = prior?.photoThumb || ''; $('#photoPreview').src = photoThumb; $('#photoPreview').classList.toggle('has-photo', Boolean(photoThumb)); $('#playerSummary').innerHTML = selected ? `<b>${esc(selected.fullName)}</b><small>${esc(selected.clubName)} · ${esc(selected.category)} · ${esc(selected.pairCode)}${selected.dupr ? ` · DUPR ${esc(selected.dupr)}` : ''}</small>` : '<span class="sub">Choose a player from the retained registration roster.</span>'; }
  function render() { if (!state) return; const rows = Object.entries(state.checkins || {}).sort(([,a],[,b]) => String(b.checkedInAt).localeCompare(String(a.checkedInAt))); $('#checkinList').innerHTML = rows.length ? rows.map(([id,player]) => `<div class="checkin-row"><img src="${player.photoThumb || ''}" alt=""><div><b>${esc(player.name)}</b><small>${esc(player.category)} · ${esc(player.pair)} · ${esc(player.clubName)} · ${esc(player.shirtSize)}</small></div><div class="checkin-status"><span class="badge">${player.waiverSigned ? 'Waiver ✓' : 'Waiver pending'} · ${esc(player.payment)}</span><button class="undo-checkin" data-undo-checkin="${esc(id)}">Undo check-in</button></div></div>`).join('') : '<p class="sub">No players checked in yet.</p>'; document.querySelectorAll('[data-undo-checkin]').forEach(button => button.onclick = () => showUndoCheckin(button.dataset.undoCheckin)); }
  function showUndoCheckin(id) { const player = state.checkins?.[id]; if (!player) return; document.body.insertAdjacentHTML('beforeend', `<div class="confirm-backdrop" id="undoCheckinModal"><section class="confirm-card undo-checkin-card"><button class="confirm-close" id="closeUndoCheckin">×</button><span class="eyebrow">Undo player arrival</span><h2>Undo ${esc(player.name)}'s check-in?</h2><p>This clears the event photo, payment, waiver, shirt-size, and arrival record. The player's retained registration remains available for check-in again.</p><div class="form-actions"><button class="action alt" id="cancelUndoCheckin">Keep check-in</button><button class="action undo-confirm" id="confirmUndoCheckin">Undo check-in</button></div></section></div>`); const close = () => $('#undoCheckinModal')?.remove(); $('#closeUndoCheckin').onclick = close; $('#cancelUndoCheckin').onclick = close; $('#confirmUndoCheckin').onclick = async () => { const button = $('#confirmUndoCheckin'); button.disabled = true; delete state.checkins[id]; try { await Promise.all([deleteCheckin(id), publishControl(state)]); close(); render(); if (selected?.id === id) choosePlayer(); toast(`${player.name}'s check-in was undone.`); } catch (_) { state.checkins[id] = player; button.disabled = false; $('#formError').textContent = 'Check-in could not be undone. Check the connection and try again.'; } }; }
  function drawImage(source, sourceWidth, sourceHeight) { const canvas = $('#photoCanvas'), size = 128; canvas.width = size; canvas.height = size; const context = canvas.getContext('2d'), scale = Math.max(size/sourceWidth,size/sourceHeight), width = sourceWidth*scale, height = sourceHeight*scale; context.clearRect(0,0,size,size); context.drawImage(source,(size-width)/2,(size-height)/2,width,height); photoThumb = canvas.toDataURL('image/jpeg',.58); $('#photoPreview').src = photoThumb; $('#photoPreview').classList.add('has-photo'); }
  async function useFile(file) { if (!file) return; const image = new Image(); image.onload = () => drawImage(image,image.width,image.height); image.src = URL.createObjectURL(file); }
  async function openCamera() { try { stream = await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:720}},audio:false}); $('#cameraPreview').srcObject = stream; $('#cameraPreview').hidden = false; $('#capturePhoto').hidden = false; $('#photoPreview').hidden = true; } catch (_) { $('#formError').textContent = 'Camera access was not available. Use Upload photo instead.'; } }
  function capture() { const video = $('#cameraPreview'); if (!video.videoWidth) return; drawImage(video,video.videoWidth,video.videoHeight); stream?.getTracks().forEach(track => track.stop()); stream = null; video.hidden = true; $('#capturePhoto').hidden = true; $('#photoPreview').hidden = false; }
  $('#staffLogin').onclick = async () => { $('#loginError').textContent = 'Signing in…'; try { await login($('#staffEmail').value.trim(),$('#staffPassword').value); } catch (_) { $('#loginError').textContent = 'Sign-in failed or this account lacks check-in access.'; } };
  $('#registeredPlayer').onchange = choosePlayer; $('#openCamera').onclick = openCamera; $('#capturePhoto').onclick = capture; $('#playerPhoto').onchange = event => useFile(event.target.files[0]);
  $('#checkinForm').onsubmit = async event => { event.preventDefault(); if (!selected) return $('#formError').textContent = 'Select a registered player.'; if (!photoThumb) return $('#formError').textContent = 'Capture or upload the player photo first.'; state.checkins ||= {}; state.checkins[selected.id] = { registrationId:selected.registrationId, playerIndex:selected.playerIndex, name:selected.fullName, shirtSize:$('#shirtSize').value, club:selected.club, clubName:selected.clubName, category:selected.category, pair:selected.pairCode, payment:$('#paymentStatus').value, waiverSigned:$('#waiverSigned').checked, photoThumb, checkedInAt:new Date().toISOString() }; try { await Promise.all([publishControl(state), publishCheckin(selected.id, state.checkins[selected.id])]); toast(`${selected.fullName} checked in.`); $('#checkinForm').reset(); selected=null; photoThumb=''; $('#photoPreview').src=''; $('#playerSummary').innerHTML=''; render(); } catch (_) { $('#formError').textContent = 'Check-in could not be synchronized to Match Control.'; } };
  watchAuth(user => { if (!user) { $('#checkinWorkspace').hidden=true; return; } $('#staffEmail').value=user.email; $('#checkinLogin').innerHTML=`<div class="session-row"><div><span class="eyebrow">Signed in</span><b>${esc(user.email)}</b></div><button class="action alt" id="staffLogout">Sign out</button></div>`; $('#staffLogout').onclick=logout; $('#checkinWorkspace').hidden=false; watchControl(incoming => { state={...incoming,checkins:{...(incoming.checkins||{}),...(state?.checkins||{})}}; render(); choosePlayer(); }, () => $('#formError').textContent='Tournament access denied.'); watchRegistrations(items => { registrations=items; fillPlayers(); }, () => $('#formError').textContent='Registration roster unavailable.'); watchCheckins(items => { if (!state) return; state.checkins = Object.fromEntries(items.map(item => [item.id, item])); render(); choosePlayer(); }, () => $('#formError').textContent='Player photos unavailable.'); });
})();
