const revision = new URL(import.meta.url).searchParams.get('v') || 'dev';
const { watchAuth, login, logout, watchControl, watchRegistrations, watchCheckins, publishControl, publishCheckin, deleteCheckin } = await import(`../firebase-sync.js?v=${encodeURIComponent(revision)}`);

(() => {
  const config = window.TOURNAMENT_CONFIG, $ = selector => document.querySelector(selector), $$ = selector => [...document.querySelectorAll(selector)], esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  let state = null, registrations = [], selected = null, photoThumb = '', stream = null, facingMode = 'environment';
  const toast = message => { const el = $('#officialToast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 1800); };
  const paymentTone = value => value === 'paid' ? 'paid' : value === 'partial' ? 'partial' : 'pending';
  function playerRecords() { return registrations.filter(reg => reg.status === 'confirmed').flatMap(reg => (reg.players || []).map((player, index) => ({ id:`${reg.id}:${index}`, registrationId:reg.id, playerIndex:index, fullName:player.fullName, email:player.email || '', category:reg.category, club:reg.club, clubName:reg.clubName, pairCode:reg.pairCode, dupr:player.dupr || '', shirtSize:player.shirtSize || 'Not set', payment:player.payment || 'pending' }))).sort((a,b) => a.fullName.localeCompare(b.fullName)); }
  function matchedPlayers() { const query = $('#playerSearch').value.trim().toLowerCase(); if (!query) return []; return playerRecords().filter(player => `${player.fullName} ${player.category} ${player.clubName} ${player.pairCode}`.toLowerCase().includes(query)).slice(0, 8); }
  function renderSearch() {
    const matches = matchedPlayers(), results = $('#playerSearchResults');
    if (!$('#playerSearch').value.trim()) { results.hidden = true; results.innerHTML = ''; return; }
    results.hidden = false; results.innerHTML = matches.length ? matches.map(player => `<button type="button" data-select-player="${esc(player.id)}"><b>${esc(player.fullName)}</b><small>${esc(player.clubName)} · ${esc(player.category)} · ${esc(player.pairCode)}</small></button>`).join('') : '<p>No matching registered players.</p>';
    $$('[data-select-player]').forEach(button => button.onclick = () => selectPlayer(button.dataset.selectPlayer));
    const query = $('#playerSearch').value.trim().toLowerCase(), exact = matches.find(player => player.fullName.toLowerCase() === query);
    if (exact || (matches.length === 1 && query.length >= 2)) selectPlayer((exact || matches[0]).id, true);
  }
  function selectPlayer(id, closeResults = true) { selected = playerRecords().find(player => player.id === id) || null; $('#registeredPlayer').value = selected?.id || ''; if (selected) $('#playerSearch').value = selected.fullName; if (closeResults) $('#playerSearchResults').hidden = true; choosePlayer(); }
  function choosePlayer() { const prior = selected && state?.checkins?.[selected.id]; photoThumb = prior?.photoThumb || ''; $('#photoPreview').src = photoThumb; $('#photoPreview').classList.toggle('has-photo', Boolean(photoThumb)); $('#waiverSigned').checked = Boolean(prior?.waiverSigned); $('#playerSummary').innerHTML = selected ? `<div><span class="player-picked">Selected player</span><b>${esc(selected.fullName)}</b><small>${esc(selected.clubName)} · ${esc(selected.category)} · ${esc(selected.pairCode)}${selected.dupr ? ` · DUPR ${esc(selected.dupr)}` : ''}</small></div><div class="registration-status"><span>Shirt <b>${esc(selected.shirtSize)}</b></span><span class="payment-status ${paymentTone(selected.payment)}">Payment <b>${esc(selected.payment)}</b></span></div>` : '<span class="sub">Search and choose a registered player.</span>'; }
  function registrationPlayerFor(checkin) { return playerRecords().find(player => player.registrationId === checkin.registrationId && Number(player.playerIndex) === Number(checkin.playerIndex)); }
  function render() { if (!state) return; const rows = Object.entries(state.checkins || {}).sort(([,a],[,b]) => String(b.checkedInAt).localeCompare(String(a.checkedInAt))); $('#checkinList').innerHTML = rows.length ? rows.map(([id,player]) => { const retained = registrationPlayerFor(player), payment = retained?.payment || player.payment || 'pending', shirt = retained?.shirtSize || player.shirtSize || 'Not set'; return `<div class="checkin-row"><img src="${player.photoThumb || ''}" alt=""><div><b>${esc(player.name)}</b><small>${esc(player.category)} · ${esc(player.pair)} · Shirt ${esc(shirt)}</small><span class="payment-status ${paymentTone(payment)}">Payment <b>${esc(payment)}</b></span></div><div class="checkin-status"><span class="waiver-badge ${player.waiverSigned ? 'verified' : 'missing'}">${player.waiverSigned ? '✓ Waiver verified' : '! Waiver missing'}</span><button class="undo-checkin" data-undo-checkin="${esc(id)}">Undo check-in</button></div></div>`; }).join('') : '<p class="sub">No players checked in yet.</p>'; $$('[data-undo-checkin]').forEach(button => button.onclick = () => showUndoCheckin(button.dataset.undoCheckin)); }
  function showUndoCheckin(id) { const player = state.checkins?.[id]; if (!player) return; document.body.insertAdjacentHTML('beforeend', `<div class="confirm-backdrop" id="undoCheckinModal"><section class="confirm-card undo-checkin-card"><button class="confirm-close contrast-close" id="closeUndoCheckin">×</button><span class="eyebrow">Undo player arrival</span><h2>Undo ${esc(player.name)}'s check-in?</h2><p>This clears the event photo, waiver, and arrival record. Retained registration details remain available.</p><div class="form-actions"><button class="action alt" id="cancelUndoCheckin">Keep check-in</button><button class="action undo-confirm" id="confirmUndoCheckin">Undo check-in</button></div></section></div>`); const close = () => $('#undoCheckinModal')?.remove(); $('#closeUndoCheckin').onclick = close; $('#cancelUndoCheckin').onclick = close; $('#confirmUndoCheckin').onclick = async () => { const button = $('#confirmUndoCheckin'); button.disabled = true; delete state.checkins[id]; try { await Promise.all([deleteCheckin(id), publishControl(state)]); close(); render(); if (selected?.id === id) choosePlayer(); toast(`${player.name}'s check-in was undone.`); } catch (_) { state.checkins[id] = player; button.disabled = false; $('#formError').textContent = 'Check-in could not be undone. Check the connection and try again.'; } }; }
  function drawImage(source, sourceWidth, sourceHeight) { const canvas = $('#photoCanvas'), size = 128; canvas.width = size; canvas.height = size; const context = canvas.getContext('2d'), scale = Math.max(size/sourceWidth,size/sourceHeight), width = sourceWidth*scale, height = sourceHeight*scale; context.clearRect(0,0,size,size); context.drawImage(source,(size-width)/2,(size-height)/2,width,height); photoThumb = canvas.toDataURL('image/jpeg',.58); $('#photoPreview').src = photoThumb; $('#photoPreview').classList.add('has-photo'); }
  async function useFile(file) { if (!file) return; const image = new Image(); image.onload = () => drawImage(image,image.width,image.height); image.src = URL.createObjectURL(file); }
  function stopCamera() { stream?.getTracks().forEach(track => track.stop()); stream = null; }
  async function openCamera() { stopCamera(); try { stream = await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facingMode},width:{ideal:1280},height:{ideal:1280}},audio:false}); $('#cameraPreview').srcObject = stream; $('#cameraPreview').hidden = false; $('#capturePhoto').hidden = false; $('#flipCamera').hidden = false; $('#photoPreview').hidden = true; $('#formError').textContent = ''; } catch (_) { $('#formError').textContent = 'Camera access was not available. Check browser permission or upload a photo.'; } }
  async function flipCamera() { facingMode = facingMode === 'user' ? 'environment' : 'user'; await openCamera(); toast(`${facingMode === 'user' ? 'Front' : 'Back'} camera selected.`); }
  function capture() { const video = $('#cameraPreview'); if (!video.videoWidth) return; drawImage(video,video.videoWidth,video.videoHeight); stopCamera(); video.hidden = true; $('#capturePhoto').hidden = true; $('#flipCamera').hidden = true; $('#photoPreview').hidden = false; }
  $('#staffLogin').onclick = async () => { $('#loginError').textContent = 'Signing in…'; try { await login($('#staffEmail').value.trim(),$('#staffPassword').value); } catch (_) { $('#loginError').textContent = 'Sign-in failed or this account lacks Check-In access.'; } };
  $('#playerSearch').oninput = renderSearch; $('#playerSearch').onkeydown = event => { if (event.key === 'Enter') { event.preventDefault(); const first = matchedPlayers()[0]; if (first) selectPlayer(first.id); } }; $('#openCamera').onclick = openCamera; $('#flipCamera').onclick = flipCamera; $('#capturePhoto').onclick = capture; $('#playerPhoto').onchange = event => useFile(event.target.files[0]);
  $('#checkinForm').onsubmit = async event => { event.preventDefault(); if (!selected) return $('#formError').textContent = 'Search and choose a registered player.'; if (!photoThumb) return $('#formError').textContent = 'Capture or upload the player photo first.'; if (!$('#waiverSigned').checked) return $('#formError').textContent = 'Verify the signed hardcopy waiver first.'; state.checkins ||= {}; state.checkins[selected.id] = { registrationId:selected.registrationId, playerIndex:selected.playerIndex, name:selected.fullName, club:selected.club, clubName:selected.clubName, category:selected.category, pair:selected.pairCode, waiverSigned:true, photoThumb, checkedInAt:new Date().toISOString() }; try { await Promise.all([publishControl(state), publishCheckin(selected.id, state.checkins[selected.id])]); toast(`${selected.fullName} checked in.`); stopCamera(); $('#checkinForm').reset(); selected=null; photoThumb=''; $('#photoPreview').src=''; $('#playerSummary').innerHTML='<span class="sub">Search and choose a registered player.</span>'; render(); } catch (_) { $('#formError').textContent = 'Check-in could not be synchronized to Match Control.'; } };
  watchAuth(user => { $('#checkinLogin').hidden=Boolean(user); $('#checkinAccount').hidden=!user; if (!user) { $('#checkinWorkspace').hidden=true; return; } $('#staffEmail').value=user.email; $('#checkinAccountEmail').textContent=user.email; $('#staffLogout').onclick=logout; $('#checkinWorkspace').hidden=false; watchControl(incoming => { state={...incoming,checkins:{...(incoming.checkins||{}),...(state?.checkins||{})}}; render(); choosePlayer(); }, () => $('#formError').textContent='Tournament access denied.'); watchRegistrations(items => { registrations=items; render(); renderSearch(); choosePlayer(); }, () => $('#formError').textContent='Registration roster unavailable.'); watchCheckins(items => { if (!state) return; state.checkins = Object.fromEntries(items.map(item=>[item.id,item])); render(); choosePlayer(); }, () => $('#formError').textContent='Player photos unavailable.'); });
  window.addEventListener('beforeunload', stopCamera);
})();
