import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-app.js';
import { getFirestore, doc, onSnapshot } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-firestore.js';
import('../cache-refresh.js?boot='+Date.now());

const firebaseConfig={apiKey:'AIzaSyBQYKgSchzlmtIGsIhf68e8OYt7Y8kY7Vo',authDomain:'ocpc-website-faf5e.firebaseapp.com',projectId:'ocpc-website-faf5e',storageBucket:'ocpc-website-faf5e.firebasestorage.app',messagingSenderId:'15833259684',appId:'1:15833259684:web:0f2f4400f9995517ae5031'};
const $=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&gt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const query=new URLSearchParams(location.search),token=String(query.get('token')||'').trim(),category=String(query.get('category')||'').trim(),pairCode=String(query.get('pair')||query.get('pairCode')||'').trim().toUpperCase();
let data=null,lastAlert='';

function fail(title,message){$('#loadingState').hidden=true;$('#content').hidden=true;$('#errorState').hidden=false;$('#errorTitle').textContent=title;$('#errorMessage').textContent=message;}
function pair(categoryValue,code){return data?.pairs?.[`${categoryValue}|${code}`]||data?.pairs?.[categoryValue]?.[code]||{};}
function names(categoryValue,code){const item=pair(categoryValue,code);return item.names||[item.player1,item.player2].filter(Boolean).join(' / ')||code;}
function time(value){if(value===null||value===undefined||Number.isNaN(Number(value)))return 'Time to be announced';const total=Number(value),hour=Math.floor(total/60)%24,minute=Math.floor(total%60);return `${hour%12||12}:${String(minute).padStart(2,'0')} ${hour>=12?'PM':'AM'}`;}
function updated(value){const raw=value?.toDate?.()||new Date(value||Date.now());return Number.isNaN(raw.valueOf())?'Live':'Updated '+new Intl.DateTimeFormat('en-PH',{hour:'numeric',minute:'2-digit',second:'2-digit'}).format(raw);}
function matches(){return (data?.playerPortal?.matches||[]).filter(match=>match.category===category&&(match.a===pairCode||match.b===pairCode));}
function activeCourt(match){return Object.entries(data?.playerPortal?.courts||{}).find(([,court])=>court.matchId===match.id)||null;}
function completed(match){return Boolean(data?.playerPortal?.scores?.[match.id]);}
function opponent(match){return match.a===pairCode?match.b:match.a;}
function standingRow(){const source=data?.pairStandings?.[category]||{},rows=Array.isArray(source)?source:Object.values(source).filter(Array.isArray).flat();return rows.map((row,index)=>({...row,rank:Number(row.rank||index+1),code:String(row.code||row.pairCode||'').toUpperCase()})).find(row=>row.code===pairCode)||null;}
function medalStatus(){const medal=data?.medals?.[category]||{},final=medal.final||{},bronze=medal.bronze||{};if(final.a===pairCode||final.b===pairCode)return {tone:'qualified',title:'Qualified for Gold / Silver',copy:'Your pair is seeded into the #1 medal match.'};if(bronze.a===pairCode||bronze.b===pairCode)return {tone:'qualified',title:'Qualified for Bronze / 4th',copy:'Your pair is seeded into the #2 medal match.'};const row=standingRow();if(!row)return {tone:'pending',title:'Standings pending',copy:'Medal qualification will update as results are confirmed.'};if(Number(row.rank)<=2)return {tone:'in-contention',title:`In medal position · #${row.rank}`,copy:'Keep this place through the final round-robin standings to qualify.'};return {tone:'outside',title:`Currently #${row.rank}`,copy:'Top two pairs from each club advance to the medal round.'};}
function matchStatus(match){const court=activeCourt(match);if(court)return {type:'called',court:Number(court[0]),paused:court[1].paused};if(completed(match))return {type:'complete'};return {type:'waiting'};}
function scheduledNextForCourt(match){const ids=data?.playerPortal?.courtSchedules?.[match.court]||[],nextId=ids.find(id=>{const item=(data?.playerPortal?.matches||[]).find(candidate=>candidate.id===id);return item&&!completed(item)&&!activeCourt(item);});return nextId===match.id;}
function nextScheduled(){return matches().filter(match=>!completed(match)&&!activeCourt(match)).sort((a,b)=>Number(a.startMinutes||Infinity)-Number(b.startMinutes||Infinity))[0]||null;}
function nextWaiting(){return matches().filter(match=>!completed(match)&&!activeCourt(match)&&scheduledNextForCourt(match)).sort((a,b)=>Number(a.startMinutes||Infinity)-Number(b.startMinutes||Infinity))[0]||null;}
function notify(kind,title,body){const key=`${kind}|${title}|${body}`;if(key===lastAlert)return;lastAlert=key;if('Notification'in window&&Notification.permission==='granted')new Notification(title,{body});if(navigator.vibrate)navigator.vibrate(kind==='called'?[120,70,180]:90);}
function renderNotice(){const live=matches().map(match=>({match,status:matchStatus(match)})).find(item=>item.status.type==='called'),next=nextWaiting(),notice=$('#notice');if(live){const {match,status}=live,paused=status.paused;notice.className='notice called';$('#noticeIcon').textContent='📣';$('#noticeKicker').textContent=paused?'Match paused':'Called to court';$('#noticeTitle').textContent=`Go to Court ${status.court}`;$('#noticeCopy').textContent=`${names(category,pairCode)} vs ${names(category,opponent(match))}${paused?' · Match is currently paused. Stay ready.':'. Please proceed to the court now.'}`;notify('called',`Court ${status.court}: you are called`,`${names(category,pairCode)} is now on court.`);return}if(next){notice.className='notice up-next';$('#noticeIcon').textContent='⚡';$('#noticeKicker').textContent='Up next';$('#noticeTitle').textContent=`Get ready for Court ${next.court||'TBA'}`;$('#noticeCopy').textContent=`Your next opponent is ${names(category,opponent(next))}. Scheduled ${time(next.startMinutes)}.`;notify('up-next','You are up next',`Be ready for Court ${next.court||'TBA'} at ${time(next.startMinutes)}.`);return}notice.className='notice waiting';$('#noticeIcon').textContent='✓';$('#noticeKicker').textContent='Schedule status';$('#noticeTitle').textContent=matches().length?'No remaining matches':'Schedule pending';$('#noticeCopy').textContent=matches().length?'Your scheduled matches are complete.':'Your pair has not been scheduled yet.';}
function renderNext(){const next=nextScheduled(),target=$('#nextMatch');if(!next){target.innerHTML='<p class="empty">No upcoming match is currently waiting.</p>';return}target.innerHTML=`<article class="match-card"><span class="match-time">${esc(time(next.startMinutes))}</span><div><small>${esc(next.category)} · Court ${esc(next.court||'TBA')}</small><b>${esc(names(category,pairCode))}</b><span>vs</span><b>${esc(names(category,opponent(next)))}</b></div></article>`;}
function renderMatches(){const rows=matches().sort((a,b)=>Number(a.startMinutes||Infinity)-Number(b.startMinutes||Infinity));$('#matchList').innerHTML=rows.length?rows.map(match=>{const status=matchStatus(match),score=data?.playerPortal?.scores?.[match.id],label=status.type==='called'?`Court ${status.court}${status.paused?' · Paused':' · Live'}`:status.type==='complete'?`Final · ${score.a}-${score.b}`:'Scheduled';return `<article class="schedule-row ${status.type}"><time>${esc(time(match.startMinutes))}</time><div><b>${esc(names(category,pairCode))}</b><span>vs ${esc(names(category,opponent(match)))}</span></div><em>${esc(label)}</em></article>`}).join(''):'<p class="empty">No match schedule has been published for this pair.</p>';}
function renderStanding(){const row=standingRow(),target=$('#standingSummary');if(!row){target.innerHTML='<p class="summary-empty">Standings will appear once the tournament is published.</p>';return}const pf=Number(row.pointsFor||0),pa=Number(row.pointsAgainst||0),diff=Number(row.diff??row.differential??pf-pa);target.innerHTML=`<div class="rank-line"><strong>#${esc(row.rank)}</strong><span>in ${esc(category)}</span></div><dl><div><dt>W-L</dt><dd>${esc(row.wins||0)}-${esc(row.losses||0)}</dd></div><div><dt>Played</dt><dd>${esc(row.played||0)}</dd></div><div><dt>+/-</dt><dd>${diff>0?'+':''}${esc(diff)}</dd></div></dl>`;}
function renderQualification(){const status=medalStatus(),target=$('#qualificationSummary');target.innerHTML=`<div class="qualification ${esc(status.tone)}"><b>${esc(status.title)}</b><p>${esc(status.copy)}</p></div>`;}
function render(){const event=data.event||{};document.title=`${names(category,pairCode)} · Matchday`;$('#eventName').textContent=event.name||'Tournament';$('#eventMeta').textContent=[event.displayDate||event.date,event.venue,event.location].filter(Boolean).join(' · ');$('#pairNames').textContent=names(category,pairCode);$('#pairMeta').textContent=`${category} · ${pairCode}`;$('#lastUpdated').textContent=updated(data.updatedAt);renderNotice();renderStanding();renderQualification();renderNext();renderMatches();$('#loadingState').hidden=true;$('#errorState').hidden=true;$('#content').hidden=false;}
if(!token||!category||!pairCode||!/^[-_A-Za-z0-9]{12,200}$/.test(token)){fail('Invalid player link','Scan your pair’s QR code again, or ask Match Control for your unique player link.');}else{const db=getFirestore(initializeApp(firebaseConfig));onSnapshot(doc(db,'tournamentPublicViews',token),snapshot=>{if(!snapshot.exists()){fail('Player link not found','Ask Match Control for a fresh player QR code.');return}const incoming=snapshot.data();if(incoming.active===false||incoming.revoked){fail('Player link is no longer active','Ask Match Control for a new player QR code.');return}data=incoming;if(!data.playerPortal){fail('Player updates are not available yet','Match Control needs to publish the latest tournament view.');return}render();if('Notification'in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{});},()=>fail('Live connection interrupted','Check your connection, then reopen your player QR link.'));}
