const revision = new URL(import.meta.url).searchParams.get('v') || 'dev';
const { loadTournamentContext } = await import(`../event-context.js?v=${encodeURIComponent(revision)}`);
await loadTournamentContext();
const { watchAuth, login, logout, authorizeTournamentTool, watchControl, watchRegistrations, createRegistration, updateRegistration, deleteRegistration, publishControl } = await import(`../firebase-sync.js?v=${encodeURIComponent(revision)}`);

(() => {
  const config = window.TOURNAMENT_CONFIG, $ = selector => document.querySelector(selector), esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  document.querySelector('.field-brand img').src = config.brand.logo; document.querySelector('.field-header>a').href = window.MATCHDAY_EVENT_URL('../control.html');
  let state = null, registrations = [], editingId = '';
  const randomPartnerMode = config.pairing?.mode === 'random-partners';
  const toast = message => { const el = $('#officialToast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 1800); };
  const opaquePairCode = (value, item = {}) => { const code = String(value || '').trim(); return !code || [item.id, item.entryId, item.stableEntryId].map(id => String(id || '').trim()).includes(code) || /^[A-Za-z0-9]{20}$/.test(code); };
  const visiblePairCode = item => { const linked = Object.values(state?.pairs || {}).find(pair => pair?.registrationId === item.id), code = String(linked?.pairCode || item.pairCode || '').trim(); return opaquePairCode(code, item) ? 'Registered pair' : code; };
  const pairDisplay = item => { const names = (item.players || []).map(player => player.fullName).filter(Boolean), team = String(item.teamName || '').trim(); return team ? `${team} (${names.join(' & ')})` : names.join(' / '); };
  const club = () => config.clubs.find(item => item.id === $('#regClub').value);
  function fillPairSlots() { if (!state || randomPartnerMode) return; const selectedClub = club(), value = state.pairCounts?.[$('#regCategory').value], count = Number(typeof value === 'object' ? value?.[selectedClub?.id] : value) || 6, prefix = selectedClub?.pairPrefix || 'O'; $('#regPair').innerHTML = Array.from({length: count}, (_, i) => `<option value="${prefix}${i+1}">${prefix}${i+1}</option>`).join(''); }
  function applyPairToRoster(registration, previous = null) {
    if (randomPartnerMode) return;
    if (previous) {
      const previousKey = `${previous.category}|${previous.pairCode}`;
      if (state.pairs[previousKey]?.registrationId === registration.id && (registration.status !== 'confirmed' || previousKey !== `${registration.category}|${registration.pairCode}`)) state.pairs[previousKey] = { player1: '', player2: '' };
    }
    if (registration.status !== 'confirmed') { publishControl(state).catch(() => toast('Registration saved, but roster unlinking failed.')); return; }
    const key = `${registration.category}|${registration.pairCode}`;
    state.pairs[key] = { player1: registration.players[0].fullName, player2: registration.players[1].fullName, teamName:registration.teamName || '', name:pairDisplay(registration), club:registration.club || '', clubName:registration.clubName || '', registrationId: registration.id || editingId };
    publishControl(state).catch(() => toast('Registration saved, but roster linking failed.'));
  }
  function render() {
    const q = $('#registrationSearch').value.trim().toLowerCase();
    const rows = registrations.filter(item => !q || `${item.category} ${item.clubName} ${item.teamName || ''} ${visiblePairCode(item)} ${item.players?.map(p => p.fullName).join(' ')}`.toLowerCase().includes(q));
    $('#registrationCount').textContent = `${registrations.length} ${randomPartnerMode ? 'players' : 'pairs'} retained in Firebase`;
    $('#registrationList').innerHTML = rows.length ? rows.map(item => `<article class="registration-row"><div><span class="badge">${esc(item.status)}</span><b>${esc(item.category)} · ${esc(item.clubName)} · ${esc(visiblePairCode(item))}</b>${item.teamName?`<small><b>${esc(pairDisplay(item))}</b></small>`:''}${item.players.map(player => `<small>${esc(player.fullName)} · Shirt ${esc(player.shirtSize || 'Not set')} · ${player.payment ? `<span class="payment-dot payment-${esc(player.payment)}">${esc(player.payment)}</span>` : 'Payment not set'}</small>`).join('')}</div><div class="row-actions"><button class="action alt" data-edit="${item.id}">Edit</button><button class="text-danger" data-delete="${item.id}">Remove</button></div></article>`).join('') : '<p class="sub">No registrations found.</p>';
    document.querySelectorAll('[data-edit]').forEach(button => button.onclick = () => edit(button.dataset.edit));
    document.querySelectorAll('[data-delete]').forEach(button => button.onclick = async () => { const item = registrations.find(row => row.id === button.dataset.delete); if (!confirm(`Remove ${pairDisplay(item)} from registration?`)) return; const key = `${item.category}|${item.pairCode}`; if (!randomPartnerMode && state.pairs[key]?.registrationId === item.id) { state.pairs[key] = { player1:'', player2:'' }; await publishControl(state); } await deleteRegistration(item.id); toast('Registration removed.'); });
  }
  function edit(id) { const item = registrations.find(row => row.id === id); if (!item) return; editingId = id; $('#formTitle').textContent = randomPartnerMode ? 'Edit individual player' : 'Edit pair'; $('#regCategory').value = item.category; $('#regClub').value = item.club; fillPairSlots(); if (!randomPartnerMode) { $('#regPair').value = item.pairCode; $('#regTeamName').value = item.teamName || ''; } $('#regStatus').value = item.status; const first=item.players?.[0]||{}; ['Name','Email','Dupr'].forEach(field => { $('#p1'+field).value = first[field === 'Name' ? 'fullName' : field.toLowerCase()] || ''; }); [1,2].forEach((number,index) => { const player=item.players?.[index]||{}; $(`#p${number}Shirt`).value = player.shirtSize || ''; $(`#p${number}Payment`).value = player.payment || ''; if (number===2) ['Name','Email','Dupr'].forEach(field => { $('#p2'+field).value = player[field === 'Name' ? 'fullName' : field.toLowerCase()] || ''; }); }); $('#cancelEdit').hidden = false; window.scrollTo({top:0,behavior:'smooth'}); }
  function resetForm() { editingId = ''; $('#registrationForm').reset(); $('#formTitle').textContent = randomPartnerMode ? 'New individual player' : 'New pair'; $('#cancelEdit').hidden = true; fillPairSlots(); }
  if (randomPartnerMode) { $('#formTitle').textContent = 'New individual player'; $('#regPair').closest('label').hidden = true; $('#regPair').required = false; $('#regTeamName').closest('label').hidden = true; const second = $('#p2Name').closest('fieldset'); if (second) second.hidden = true; $('#p2Name').required = false; document.querySelector('main h1').textContent = 'Register players'; document.querySelector('main .sub').textContent = 'Players register individually. Matchday will shuffle eligible players into proposed pairs, show the draw for review, and keep each pair fixed after the organizer locks it.'; document.querySelector('.list-heading h2').textContent = 'Registered players'; }
  config.categories.forEach(category => $('#regCategory').insertAdjacentHTML('beforeend', `<option>${esc(category)}</option>`));
  config.clubs.forEach(item => $('#regClub').insertAdjacentHTML('beforeend', `<option value="${item.id}">${esc(item.name)}</option>`));
  ['#p1Email', '#p2Email'].forEach(selector => { $(selector).required = false; $(selector).parentElement.firstChild.textContent = 'Email (optional)'; });
  $('#regCategory').onchange = fillPairSlots; $('#regClub').onchange = fillPairSlots; $('#registrationSearch').oninput = render; $('#cancelEdit').onclick = resetForm;
  $('#staffLogin').onclick = async () => { $('#loginError').textContent = 'Signing in…'; try { await login($('#staffEmail').value.trim(), $('#staffPassword').value); } catch (_) { $('#loginError').textContent = 'Sign-in failed or this account lacks registration access.'; } };
  $('#registrationForm').onsubmit = async event => { event.preventDefault(); const selectedClub = club(), players = [{ fullName: $('#p1Name').value.trim(), email: $('#p1Email').value.trim().toLowerCase(), dupr: $('#p1Dupr').value.trim(), shirtSize: $('#p1Shirt').value, payment: $('#p1Payment').value }]; if (!randomPartnerMode) players.push({ fullName: $('#p2Name').value.trim(), email: $('#p2Email').value.trim().toLowerCase(), dupr: $('#p2Dupr').value.trim(), shirtSize: $('#p2Shirt').value, payment: $('#p2Payment').value }); const data = { category: $('#regCategory').value, club: selectedClub.id, clubName: selectedClub.name, pairCode: randomPartnerMode ? '' : $('#regPair').value, teamName: randomPartnerMode ? '' : $('#regTeamName').value.trim(), status: $('#regStatus').value, registrationUnit: randomPartnerMode ? 'individual' : 'pair', pairingStatus: randomPartnerMode ? 'unpaired' : 'fixed', players }; const duplicate = registrations.find(row => row.id !== editingId && row.category === data.category && row.club === data.club && (randomPartnerMode ? (row.players?.[0]?.email && row.players[0].email === data.players[0].email) || (row.players?.[0]?.fullName && row.players[0].fullName.toLowerCase() === data.players[0].fullName.toLowerCase()) : row.pairCode === data.pairCode) && row.status !== 'withdrawn'); if (duplicate) return $('#formError').textContent = randomPartnerMode ? 'That player is already registered in this category.' : `${data.pairCode} is already assigned in this category.`; const duplicateTeam=data.teamName&&registrations.find(row=>row.id!==editingId&&row.status!=='withdrawn'&&String(row.teamName||'').trim().toLowerCase()===data.teamName.toLowerCase());if(duplicateTeam)return $('#formError').textContent=`${data.teamName} is already used by another pair.`; try { if (editingId) { const previous = registrations.find(row => row.id === editingId); await updateRegistration(editingId, data); applyPairToRoster({...data,id:editingId}, previous); } else { const result = await createRegistration(data); applyPairToRoster({...data,id:result.id}); } resetForm(); $('#formError').textContent = ''; toast(randomPartnerMode ? 'Player securely registered.' : 'Registration securely saved.'); } catch (_) { $('#formError').textContent = 'Could not save. Confirm this account has Match Control access.'; } };
  watchAuth(async user => {
    $('#registrationWorkspace').hidden = true;
    if (!user) { $('#registrationLogin').hidden = false; $('#registrationSession')?.remove(); $('#loginError').textContent = ''; return; }
    $('#staffEmail').value = user.email; $('#loginError').textContent = `Signed in as ${user.email}. Verifying Registration Desk access…`;
    let access; try { access = await authorizeTournamentTool(user, ['tournament_registration']); } catch (_) {}
    if (!access?.allowed) { $('#registrationLogin').hidden = false; $('#loginError').textContent = 'Signed in, but Registration Desk permission is missing for this tournament.'; return; }
    watchControl(incoming => { state = incoming; fillPairSlots(); }, () => { $('#loginError').textContent = 'This account cannot read the tournament. Sign out and use an authorized account.'; });
    watchRegistrations(items => { registrations = items; $('#registrationLogin').hidden = true; if (!$('#registrationSession')) $('#registrationWorkspace').insertAdjacentHTML('beforebegin', `<section class="field-card session-row" id="registrationSession"><div><span class="eyebrow">Registration Desk active</span><b>${esc(user.email)}</b></div><button class="action alt" id="registrationLogout" type="button">Switch account</button></section>`); $('#registrationLogout').onclick = logout; $('#registrationWorkspace').hidden = false; render(); }, () => { $('#registrationLogin').hidden = false; if (!$('#staffLogout')) { $('#staffLogin').insertAdjacentHTML('afterend', '<button class="action alt" id="staffLogout" type="button">Sign out / switch account</button>'); $('#staffLogout').onclick = logout; } $('#loginError').textContent = 'Signed in, but Registration Desk permission is missing. An administrator must grant it in Match Control → Settings.'; });
  });
})();
