const revision = new URL(import.meta.url).searchParams.get('v') || 'dev';
const { loadTournamentContext } = await import(`../event-context.js?v=${encodeURIComponent(revision)}`);
await loadTournamentContext();
const { watchAuth, watchControl, watchMatches, watchCheckins } = await import(`../firebase-sync.js?v=${encodeURIComponent(revision)}`);

(() => {
  const c=window.TOURNAMENT_CONFIG,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],params=new URLSearchParams(location.search),esc=v=>String(v??'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x])); let state=null,view=params.get('view')||'arena',focus=Number(params.get('court'))||1,cast=params.get('cast')==='1',demo=params.get('demo')==='1';
  const categoryClass=cat=>cat==='Novice'?'novice':cat==='Low Intermediate'?'low':'high';
  function elapsed(x){return(x?.elapsed||0)+(x?.running&&x.startedAt?Math.max(0,Math.floor((Date.now()-x.startedAt)/1000)):0)}
  function timer(s){const over=s>900,shown=over?s-900:s;return`${over?'+':''}${String(Math.floor(shown/60)).padStart(2,'0')}:${String(shown%60).padStart(2,'0')}`}
  function pair(cat,code){const p=state?.pairs?.[`${cat}|${code}`]||{};return[p.player1||`${code} Player 1`,p.player2||`${code} Player 2`]}
  function photo(cat,code,club,index){return Object.values(state?.checkins||{}).find(item=>item.category===cat&&item.pair===code&&item.club===club&&Number(item.playerIndex)===index)?.photoThumb||''}
  function prefix(cat){if(cat==='Novice')return'NOV';if(cat==='Low Intermediate')return'LOW';if(cat==='High Intermediate')return'HIGH';return String(cat).replace(/[^a-z0-9 ]/gi,'').split(/\s+/).filter(Boolean).map(word=>word[0]).join('').slice(0,4).toUpperCase()||'CAT'}
  function playerMarkup(cat,code,club,live,side){return pair(cat,code).map((name,index)=>{const image=photo(cat,code,club,index),serving=live?.serving===side&&Number(live.serverPlayer||0)===index;return`<span class="broadcast-player ${serving?'serving':''}">${image?`<img src="${image}" alt="">`:'<i></i>'}<b>${serving?'● ':''}${esc(name)}</b></span>`}).join('')}
  const clubName=id=>c.clubs.find(club=>club.id===id)?.short||id;
  function courtCard(no){const court=state?.courts?.[no]||{},match=state?.matches?.find(m=>m.id===court.matchId);if(!match)return`<article class="modern-court vacant"><header><span>COURT ${no}</span><b>AVAILABLE</b></header><div class="vacant-message"><i>✓</i><strong>Ready for play</strong><small>Waiting for Match Control</small></div></article>`;const live=state.liveScoring?.[match.id]||court,score=state.scores?.[match.id]||live,complete=Boolean(state.scores?.[match.id]),official=state.refereeAssignments?.[match.id],status=complete?'FINAL':live.interruption?.active?String(live.interruption.label||'TIMEOUT').toUpperCase():live.running?'LIVE':elapsed(live)?'PAUSED':'READY',interruption=live.interruption?.active?(String(live.interruption.type).startsWith('timeout-')?'broadcast-timeout-team':['medical'].includes(live.interruption.type)?'broadcast-timeout-danger':'broadcast-timeout-warning'):'';return`<article class="modern-court ${categoryClass(match.category)} ${live.running?'is-live':''} ${interruption}"><header><span>COURT ${no}</span><b>${status}</b><small>${esc(match.category)}</small></header><div class="broadcast-match-id">${esc(match.id)} ${official?`· OFFICIATED BY ${esc(official.split('@')[0])}`:'· PLAYER-REPORTED'}</div><section class="broadcast-versus"><div class="broadcast-side ocpc"><small>${esc(clubName('ocpc'))} · ${prefix(match.category)}-${match.a}</small><div class="broadcast-players">${playerMarkup(match.category,match.a,'ocpc',live,'a')}</div></div><div class="broadcast-score"><b>${score?.a??0}</b><span>:</span><b>${score?.b??0}</b></div><div class="broadcast-side rebels"><small>${esc(clubName('rebels'))} · ${prefix(match.category)}-${match.b}</small><div class="broadcast-players">${playerMarkup(match.category,match.b,'rebels',live,'b')}</div></div></section><footer><span>${official&&live.serving?`${esc(clubName(live.serving==='a'?'ocpc':'rebels'))} SERVING`:'SCORE STATUS'}</span><b>${timer(elapsed(live))}</b></footer></article>`}
  function completedCount(){return state?.matches?.filter(match=>state.scores?.[match.id]).length||0}
  function clubWins(){const wins={ocpc:0,rebels:0};state?.matches?.forEach(match=>{const score=state.scores?.[match.id];if(!score)return;Number(score.a)>Number(score.b)?wins.ocpc++:wins.rebels++});return wins}
  function render(){if(!state)return;document.body.classList.toggle('cast-mode',cast);document.body.dataset.view=view;const courts=Array.from({length:c.event.courts},(_,i)=>i+1),visible=view==='focus'?[focus]:courts;$('#broadcastGrid').innerHTML=visible.map(courtCard).join('');const wins=clubWins(),active=courts.filter(no=>state.courts?.[no]?.matchId).length;$('#broadcastPulse').innerHTML=`<div><span>Courts active</span><b>${active}/${c.event.courts}</b></div><div><span>Matches complete</span><b>${completedCount()}/${state.matches.length}</b></div><div class="club-pulse"><span>Club wins</span><b>${esc(clubName('ocpc'))} ${wins.ocpc} <i>:</i> ${wins.rebels} ${esc(clubName('rebels'))}</b></div>`;const queued=(state.queue||[]).filter(id=>!state.scores?.[id]).slice(0,8).map(id=>state.matches.find(match=>match.id===id)).filter(Boolean);$('#broadcastTicker').innerHTML=queued.length?queued.map(match=>`<span><b>${esc(pair(match.category,match.a).join(' / '))}</b> vs <b>${esc(pair(match.category,match.b).join(' / '))}</b> · ${esc(match.category)}</span>`).join(''):'<span>Schedule complete</span>';$$('[data-broadcast-view]').forEach(button=>button.classList.toggle('active',button.dataset.broadcastView===view));$('#focusCourt').value=String(focus)}
  function updateClock(){const parts=new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',hour:'numeric',minute:'2-digit',second:'2-digit'}).format(new Date());$('#broadcastClock').textContent=parts}
  $('#eventName').textContent=c.event.name;$('#eventMeta').textContent=`${c.event.displayDate} · ${c.event.venue}, ${c.event.location}`;document.querySelector('.broadcast-hero h1').textContent=`${c.clubs[0].short} × ${c.clubs[1].short}`;document.querySelector('.field-brand img').src=c.brand.logo;$('#focusCourt').innerHTML=Array.from({length:c.event.courts},(_,index)=>`<option value="${index+1}">Court ${index+1}</option>`).join('');document.querySelector('.broadcast-gate a').href=window.MATCHDAY_EVENT_URL('../control.html');$$('[data-broadcast-view]').forEach(button=>button.onclick=()=>{view=button.dataset.broadcastView;render()});$('#focusCourt').onchange=event=>{focus=Number(event.target.value);view='focus';render()};$('#fullscreenBroadcast').onclick=()=>document.documentElement.requestFullscreen?.();$('#openCast').onclick=()=>window.open(window.MATCHDAY_EVENT_URL(location.pathname,{cast:'1',view,court:focus}),'matchday-live-cast','noopener');if(cast)$('#broadcastControl').hidden=true;
  if(demo){try{state=JSON.parse(localStorage.getItem(`${c.storageKey}.demo`));}catch(_){}$('#broadcastGate').hidden=true;render();window.addEventListener('storage',event=>{if(event.key===`${c.storageKey}.demo`&&event.newValue){state=JSON.parse(event.newValue);render()}})}else watchAuth(user=>{if(!user){$('#broadcastGate').hidden=false;return}$('#broadcastGate').hidden=true;watchControl(incoming=>{state={...incoming,liveScoring:state?.liveScoring||{},checkins:state?.checkins||{}};render()});watchMatches(items=>{if(!state)return;state.liveScoring={};items.forEach(item=>{if(item.live)state.liveScoring[item.id]=item.live;if(item.score)state.scores[item.id]=item.score});render()});watchCheckins(items=>{if(!state)return;state.checkins=Object.fromEntries(items.map(item=>[item.id,item]));render()})});setInterval(()=>{updateClock();render()},1000);updateClock();
})();
