import { watchAuth, login, logout, watchControl, watchMatches, publishMatch } from '../firebase-sync.js';

(() => {
  const config=window.TOURNAMENT_CONFIG,$=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); let state=null,user=null;
  const names=(category,code)=>{const pair=state.pairs[`${category}|${code}`]||{};return[pair.player1,pair.player2].filter(Boolean).join(' / ')||'Players not assigned'};
  const display=(category,code)=>`${category==='Novice'?'NOV':category==='Low Intermediate'?'LOW':'HIGH'}-${code}`;
  const toast=message=>{const el=$('#officialToast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1800)};
  function pendingMatches(){return(state?.matches||[]).filter(match=>{const score=state.scores?.[match.id];return !(score&&score.a!==''&&score.b!=='')}).sort((a,b)=>a.wave-b.wave||a.court-b.court)}
  function renderList(){const current=$('#kioskMatch').value;$('#kioskMatch').innerHTML='<option value="">Choose match</option>'+pendingMatches().map(match=>`<option value="${match.id}">${match.time} · ${match.id} · ${display(match.category,match.a)} vs ${display(match.category,match.b)}</option>`).join('');$('#kioskMatch').value=current;renderMatch()}
  function renderMatch(){const match=state?.matches?.find(item=>item.id===$('#kioskMatch').value);$('#scoreReportForm').hidden=!match;if(!match){$('#kioskMatchup').innerHTML='';return;}$('#kioskMatchup').innerHTML=`<article><span>OCPC · ${display(match.category,match.a)}</span><b>${esc(names(match.category,match.a))}</b></article><strong>VS</strong><article><span>Rally Rebels · ${display(match.category,match.b)}</span><b>${esc(names(match.category,match.b))}</b></article>`;$('#kioskScoreA').value='';$('#kioskScoreB').value='';$('#confirmA').checked=false;$('#confirmB').checked=false;$('#formError').textContent=''}
  $('#staffLogin').onclick=async()=>{$('#loginError').textContent='Signing in…';try{await login($('#staffEmail').value.trim(),$('#staffPassword').value)}catch(_){ $('#loginError').textContent='Sign-in failed or this account lacks score-desk access.'}};
  $('#kioskMatch').onchange=renderMatch;
  $('#scoreReportForm').onsubmit=async event=>{event.preventDefault();const match=state.matches.find(item=>item.id===$('#kioskMatch').value),a=Number($('#kioskScoreA').value),b=Number($('#kioskScoreB').value);if(!$('#confirmA').checked||!$('#confirmB').checked)return $('#formError').textContent='Both pair representatives must confirm the result.';if(a===b||Math.max(a,b)!==11||Math.min(a,b)<0)return $('#formError').textContent='Enter a valid final score. Winner must reach 11 and the match cannot end tied.';const prior=state.scores?.[match.id];if(prior&&!confirm(`A result already exists: ${prior.a}-${prior.b}. Send a replacement report?`))return;const live={...(state.liveScoring?.[match.id]||{}),a,b,running:false,startedAt:null,complete:true};const score={a,b,confirmation:{source:'player-kiosk',submittedBy:user.email,submittedAt:new Date().toISOString(),ocpcConfirmed:true,rebelsConfirmed:true}};try{await publishMatch(match.id,live,score);toast('Confirmed score sent to Match Control.');$('#kioskMatch').value='';renderList()}catch(_){$('#formError').textContent='Score could not be sent. Ask Match Control to enter it manually.'}};
  watchAuth(account=>{user=account;if(!account){$('#kioskWorkspace').hidden=true;return;}$('#staffEmail').value=account.email;$('#kioskLogin').innerHTML=`<div class="session-row"><div><span class="eyebrow">Score desk signed in</span><b>${esc(account.email)}</b></div><button class="action alt" id="staffLogout">Sign out</button></div>`;$('#staffLogout').onclick=logout;$('#kioskWorkspace').hidden=false;watchControl(incoming=>{state={...incoming,liveScoring:state?.liveScoring||{}};renderList()},()=>$('#formError').textContent='Tournament access denied.');watchMatches(items=>{if(!state)return;state.liveScoring={};items.forEach(item=>{if(item.live)state.liveScoring[item.id]=item.live;if(item.score)state.scores[item.id]=item.score});renderList()})});
})();
