import { initializeApp, getApps, getApp } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut, setPersistence, browserLocalPersistence } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-auth.js';
import { getFirestore, doc, collection, getDoc, getDocs, query, where, setDoc, writeBatch, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyBQYKgSchzlmtIGsIhf68e8OYt7Y8kY7Vo',authDomain:'ocpc-website-faf5e.firebaseapp.com',projectId:'ocpc-website-faf5e',storageBucket:'ocpc-website-faf5e.firebasestorage.app',messagingSenderId:'15833259684',appId:'1:15833259684:web:0f2f4400f9995517ae5031'};
const LEGACY_ID='ocpc-rally-rebels-dual-meet-2026',app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let user=null,profile=null,events=[];
const superAdmin=email=>['ocpc.pickleball@gmail.com','jamescastillo37@gmail.com'].includes(String(email||'').toLowerCase());
const rolesOf=value=>new Set([...(Array.isArray(value?.roles)?value.roles:[]),...(value?.role?[value.role]:[])]);
const organizerApproved=()=>superAdmin(user?.email)||rolesOf(profile).has('admin')||rolesOf(profile).has('tournament_organizer');
const tournamentRole=()=>['tournament_admin','match_control','court_manager','tournament_registration','tournament_checkin','tournament_score_desk','tournament_referee'].some(role=>rolesOf(profile).has(role));
const legacyManager=()=>superAdmin(user?.email)||['admin','tournament_admin','match_control','court_manager'].some(role=>rolesOf(profile).has(role));
const titleCase=value=>value.replace(/\b\w/g,char=>char.toUpperCase());
const minutes=value=>{const [h,m]=value.split(':').map(Number);return h*60+m};
const timeLabel=value=>{const [h,m]=value.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`};
const slug=value=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,48)||'tournament';
async function ensureSelfDirectory(){const email=String(user.email||'').trim().toLowerCase(),name=[profile?.firstName,profile?.lastName].filter(Boolean).join(' ')||email;await setDoc(doc(db,'tournamentAccountDirectory',email),{uid:user.uid,email,name,firstName:profile?.firstName||'',lastName:profile?.lastName||'',updatedAt:serverTimestamp()},{merge:true})}
function eventLink(id,path='control.html'){const url=new URL(path,location.href);url.searchParams.set('event',id);return url.href}
function safeReturn(){const value=new URLSearchParams(location.search).get('return');if(!value)return '';try{const url=new URL(value,location.origin);return url.origin===location.origin&&url.pathname.startsWith('/tournament/')&&!['/tournament/','/tournament/index.html'].includes(url.pathname)?url.href:''}catch(_){return ''}}
function legacyConfig(){return {appName:'Matchday',storageKey:`matchday.${LEGACY_ID}`,firebaseEventId:LEGACY_ID,brand:{organizer:'One Cavite Pickleball Club',shortName:'OCPC',logo:'/assets/logo-2026.png',primary:'#005E89',primaryDark:'#003F5E',accent:'#4FB6FF',highlight:'#B6FF3C',gold:'#FFC24B'},event:{name:'OCPC x Rally Rebels Club Dual Meet',date:'2026-09-19',displayDate:'September 19, 2026',venue:'Rally District PH',location:'Kawit, Cavite',startTime:'10:30 AM',endTime:'5:00 PM',courts:5,slotMinutes:15,roundRobinStartMinutes:630,roundRobinWaves:19},clubs:[{id:'ocpc',name:'One Cavite Pickleball Club',short:'OCPC',pairPrefix:'O'},{id:'rebels',name:'Rally Rebels Club',short:'Rally Rebels',pairPrefix:'R'}],categories:['Novice','Low Intermediate','High Intermediate'],pairsPerCategory:{Novice:{ocpc:6,rebels:6},'Low Intermediate':{ocpc:6,rebels:7},'High Intermediate':{ocpc:6,rebels:6}},scoring:{type:'Side-out scoring',target:11,hardCap:11,note:'Side-out scoring to 11, win by 2. At 10-10, play one sudden-death point to decide the match.',warningSeconds:540,dangerSeconds:840,targetSeconds:900}}}
async function ensureLegacyAccess(){if(!user||!legacyManager())return;const eventRef=doc(db,'tournamentEvents',LEGACY_ID),snap=await getDoc(eventRef),batch=writeBatch(db),allowed=['tournament_admin','match_control','court_manager','tournament_registration','tournament_checkin','tournament_score_desk','tournament_referee'],people=superAdmin(user.email)?(await getDocs(collection(db,'players'))).docs.map(item=>({id:item.id,...item.data()})).filter(item=>[...rolesOf(item)].some(role=>allowed.includes(role)||role==='admin')):[{id:user.uid,...profile,email:user.email}],memberIds=new Set(snap.data()?.memberIds||[]),refereeEmails=new Set(snap.data()?.refereeEmails||[]);for(const person of people){const personRoles=[...rolesOf(person)].filter(role=>allowed.includes(role)||role==='admin');if(person.id===user.uid&&superAdmin(user.email))personRoles.push('owner','tournament_admin');if(!personRoles.length)continue;memberIds.add(person.id);if(personRoles.includes('tournament_referee')&&person.email)refereeEmails.add(person.email.toLowerCase());const displayName=[person.firstName,person.lastName].filter(Boolean).join(' ')||person.email,email=String(person.email||'').toLowerCase();batch.set(doc(eventRef,'members',person.id),{uid:person.id,email,name:displayName,firstName:person.firstName||'',lastName:person.lastName||'',roles:[...new Set(personRoles)],updatedAt:serverTimestamp()},{merge:true});batch.set(doc(db,'tournamentAccess',person.id,'events',LEGACY_ID),{eventId:LEGACY_ID,name:'OCPC x Rally Rebels Club Dual Meet',date:'2026-09-19',venue:'Rally District PH',location:'Kawit, Cavite',status:'upcoming',primary:'#005E89',role:personRoles.includes('owner')?'owner':personRoles[0]||'staff',updatedAt:serverTimestamp()},{merge:true});if(email)batch.set(doc(db,'tournamentAccountDirectory',email),{uid:person.id,email,name:displayName,firstName:person.firstName||'',lastName:person.lastName||'',updatedAt:serverTimestamp()},{merge:true})}batch.set(eventRef,{ownerId:snap.data()?.ownerId||user.uid,memberIds:[...memberIds],refereeEmails:[...refereeEmails],metadata:{name:'OCPC x Rally Rebels Club Dual Meet',date:'2026-09-19',venue:'Rally District PH',location:'Kawit, Cavite',status:'upcoming'},config:legacyConfig(),updatedAt:serverTimestamp()},{merge:true});await batch.commit()}
async function loadEvents(){await ensureLegacyAccess();const snap=await getDocs(collection(db,'tournamentAccess',user.uid,'events'));events=snap.docs.map(item=>({id:item.id,...item.data()}));if(tournamentRole()&&!events.some(item=>item.id===LEGACY_ID))events.push({id:LEGACY_ID,name:'OCPC x Rally Rebels Club Dual Meet',date:'2026-09-19',venue:'Rally District PH',location:'Kawit, Cavite',status:'upcoming',primary:'#005E89',role:'assigned staff'});events.sort((a,b)=>String(b.date).localeCompare(String(a.date)));render()}
function render(){const create=$('#createTournamentBtn');create.hidden=!organizerApproved();$('#tournamentGrid').innerHTML=events.length?events.map(event=>`<article class="event-card" style="--card-brand:${esc(event.primary||'#06658c')}"><span class="status">${esc(event.status||'Private event')}</span><h3>${esc(event.name)}</h3><p>${esc(event.date||'Date to be set')}<br>${esc(event.venue||'Venue to be set')}${event.location?`, ${esc(event.location)}`:''}<br>Access: ${esc(titleCase(String(event.role||'staff').replaceAll('_',' ')))}</p><footer><a class="btn" href="${eventLink(event.id)}">Open Match Control</a></footer></article>`).join(''):'<div class="empty-card"><h3>No tournaments yet</h3><p>Your owned and assigned tournaments will appear here.</p></div>'}
$('#portalLogin').onsubmit=async event=>{event.preventDefault();$('#loginError').textContent='Signing in…';try{await setPersistence(auth,browserLocalPersistence);await signInWithEmailAndPassword(auth,$('#portalEmail').value.trim(),$('#portalPassword').value)}catch(_){$('#loginError').textContent='The email or password is incorrect, or this account is not approved.'}};
$('#portalLogout').onclick=()=>signOut(auth);$('#createTournamentBtn').onclick=()=>$('#createModal').hidden=false;$('#closeCreate').onclick=()=>$('#createModal').hidden=true;$('#createModal').onclick=event=>{if(event.target===$('#createModal'))$('#createModal').hidden=true};
$('#createTournamentForm').onsubmit=async event=>{event.preventDefault();if(!organizerApproved())return $('#createError').textContent='OCPC administrator approval is required before creating tournaments.';const name=$('#newName').value.trim(),date=$('#newDate').value,start=$('#newStart').value,end=$('#newEnd').value,categories=$('#newCategories').value.split(',').map(value=>value.trim()).filter(Boolean),eventId=`${slug(name)}-${date}-${crypto.getRandomValues(new Uint16Array(1))[0].toString(16)}`,club1=$('#newClub1').value.trim(),club2=$('#newClub2').value.trim(),primary=$('#newColor').value,courts=Math.max(1,Number($('#newCourts').value)||1),config={appName:'Matchday',firebaseEventId:eventId,storageKey:`matchday.${eventId}`,brand:{organizer:$('#newOrganizer').value.trim(),shortName:$('#newOrganizer').value.trim().slice(0,16),logo:'/assets/logo-2026.png',primary,primaryDark:'#06364D',accent:'#4FB6FF',highlight:'#B6FF3C',gold:'#FFC24B'},event:{name,date,displayDate:new Date(`${date}T12:00:00`).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}),venue:$('#newVenue').value.trim(),location:$('#newLocation').value.trim(),startTime:timeLabel(start),endTime:timeLabel(end),courts,slotMinutes:15,roundRobinStartMinutes:minutes(start),roundRobinWaves:1},clubs:[{id:'ocpc',name:club1,short:club1,pairPrefix:'O'},{id:'rebels',name:club2,short:club2,pairPrefix:'R'}],categories,pairsPerCategory:Object.fromEntries(categories.map(category=>[category,{ocpc:6,rebels:6}])),scoring:{type:'Side-out scoring',target:11,hardCap:11,note:'Side-out scoring to 11, win by 2. At 10-10, play one sudden-death point.',warningSeconds:540,dangerSeconds:840,targetSeconds:900}};$('#createError').textContent='Creating private workspace…';try{const eventRef=doc(db,'tournamentEvents',eventId),batch=writeBatch(db);batch.set(eventRef,{ownerId:user.uid,memberIds:[user.uid],refereeEmails:[],metadata:{name,date,venue:config.event.venue,location:config.event.location,status:'draft',primary},config,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});batch.set(doc(eventRef,'members',user.uid),{uid:user.uid,email:user.email.toLowerCase(),name:[profile?.firstName,profile?.lastName].filter(Boolean).join(' ')||user.email,roles:['owner','tournament_admin'],createdAt:serverTimestamp(),updatedAt:serverTimestamp()});batch.set(doc(db,'tournamentAccess',user.uid,'events',eventId),{eventId,name,date,venue:config.event.venue,location:config.event.location,status:'draft',primary,role:'owner',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await batch.commit();location.href=eventLink(eventId)}catch(error){console.error(error);$('#createError').textContent='Tournament could not be created. The updated Firebase rules may still need to be deployed.'}};
onAuthStateChanged(auth,async current=>{user=current;$('#loginGate').hidden=Boolean(user);$('#portalWorkspace').hidden=!user;if(!user){events=[];return}$('#portalIdentity').textContent=user.email;try{const snap=await getDoc(doc(db,'players',user.uid));profile=snap.exists()?snap.data():{};await ensureSelfDirectory();await loadEvents();const destination=safeReturn();if(destination)location.replace(destination);else if(new URLSearchParams(location.search).has('denied'))$('#tournamentGrid').insertAdjacentHTML('afterbegin','<div class="empty-card warning-card"><h3>That tournament is not assigned to this account</h3><p>Choose an event below or ask its owner to grant access.</p></div>')}catch(error){console.error(error);$('#tournamentGrid').innerHTML='<div class="empty-card"><h3>Portal access unavailable</h3><p>The updated Firebase rules may still need to be deployed.</p></div>'}});
