import { buildStandardDivision } from './format-setup.js';
import { initializeApp, getApps, getApp } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-app.js';
import './cache-refresh.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut, setPersistence, browserLocalPersistence } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-auth.js';
import { getFirestore, initializeFirestore, persistentLocalCache, persistentMultipleTabManager, doc, collection, getDoc, getDocs, query, where, setDoc, updateDoc, writeBatch, deleteDoc, serverTimestamp, runTransaction, onSnapshot } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-firestore.js';
import { createSessionLock } from './session-lock.js?v=portal-recovery-20260924';

const firebaseConfig={apiKey:'AIzaSyBQYKgSchzlmtIGsIhf68e8OYt7Y8kY7Vo',authDomain:'ocpc-website-faf5e.firebaseapp.com',projectId:'ocpc-website-faf5e',storageBucket:'ocpc-website-faf5e.firebasestorage.app',messagingSenderId:'15833259684',appId:'1:15833259684:web:0f2f4400f9995517ae5031'};
const LEGACY_ID='ocpc-rally-rebels-dual-meet-2026',app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=(()=>{try{return initializeFirestore(app,{localCache:persistentLocalCache({tabManager:persistentMultipleTabManager()})})}catch(_){return getFirestore(app)}})(),$=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const sessionLock=createSessionLock({db,auth,doc,onSnapshot,runTransaction,setDoc,deleteDoc,serverTimestamp,signOut});
navigator.serviceWorker?.register('/tournament/sw.js', {scope:'/tournament/'}).catch(()=>{});
let user=null,profile=null,events=[];
const superAdmin=email=>['ocpc.pickleball@gmail.com','jamescastillo37@gmail.com'].includes(String(email||'').toLowerCase());
const rolesOf=value=>new Set([...(Array.isArray(value?.roles)?value.roles:[]),...(value?.role?[value.role]:[])]);
const organizerApproved=()=>superAdmin(user?.email)||rolesOf(profile).has('admin')||rolesOf(profile).has('tournament_organizer')||profile?.organizerStatus==='approved';
const EVENT_ROLES=['owner','tournament_admin','match_control','tournament_registration','tournament_checkin','tournament_score_desk','tournament_referee'];
const ROLE_LABELS={owner:'Owner',admin:'OCPC Admin',tournament_admin:'Full Match Control',match_control:'Match Control',tournament_registration:'Registration',tournament_checkin:'Player Check-In',tournament_score_desk:'Score Desk',tournament_referee:'Referee'};
const TOOL_DEFINITIONS=[
  {id:'control',role:'control',path:'control.html',label:'Manage Tournament',operationalLabel:'Open Match Control',icon:'MC',description:'Run courts, schedules, standings and matchday operations.'},
  {id:'referee',role:'tournament_referee',path:'referee/',label:'Referee App',icon:'R',description:'View assignments and score officiated matches.'},
  {id:'registration',role:'tournament_registration',path:'registration/',label:'Registration Desk',icon:'RG',description:'Register pairs and maintain player information.'},
  {id:'checkin',role:'tournament_checkin',path:'check-in/?mode=staff',label:'Player Check-In',icon:'CI',description:'Run the staff desk or open the client-facing kiosk.'},
  {id:'score',role:'tournament_score_desk',path:'score-kiosk/',label:'Score Kiosk',icon:'SK',description:'Submit and confirm scores from unofficiated courts.'},
  {id:'broadcast',role:'broadcast',path:'broadcast/',label:'Live Broadcast',icon:'LIVE',description:'Open the live court and spectator display.'}
];
const profileEventRoles=()=>[...rolesOf(profile)].filter(role=>EVENT_ROLES.includes(role));
const tournamentRole=()=>profileEventRoles().length>0;
const legacyManager=()=>superAdmin(user?.email)||['admin','tournament_admin','match_control'].some(role=>rolesOf(profile).has(role));
const titleCase=value=>value.replace(/\b\w/g,char=>char.toUpperCase());
const minutes=value=>{const [h,m]=value.split(':').map(Number);return h*60+m};
const timeLabel=value=>{const [h,m]=value.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`};
const slug=value=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,48)||'tournament';
async function ensureSelfDirectory(){const email=String(user.email||'').trim().toLowerCase(),name=profile?.displayName||[profile?.firstName,profile?.lastName].filter(Boolean).join(' ')||email;await setDoc(doc(db,'tournamentAccountDirectory',email),{uid:user.uid,email,name,firstName:profile?.firstName||'',lastName:profile?.lastName||'',updatedAt:serverTimestamp()},{merge:true})}
function eventLink(id,path='control.html'){const url=new URL(path,location.href);url.searchParams.set('event',id);return url.href}
function safeReturn(){const value=new URLSearchParams(location.search).get('return');if(!value)return '';try{const url=new URL(value,location.origin);return url.origin===location.origin&&url.pathname.startsWith('/tournament/')&&!['/tournament/','/tournament/index.html'].includes(url.pathname)?url.href:''}catch(_){return ''}}
function legacyConfig(){return {appName:'Matchday',storageKey:`matchday.${LEGACY_ID}`,firebaseEventId:LEGACY_ID,brand:{organizer:'One Cavite Pickleball Club',shortName:'OCPC',logo:'/assets/logo-2026.png',primary:'#005E89',primaryDark:'#003F5E',accent:'#4FB6FF',highlight:'#B6FF3C',gold:'#FFC24B'},event:{name:'OCPC x Rally Rebels Club Dual Meet',date:'2026-09-19',displayDate:'September 19, 2026',venue:'Rally District PH',location:'Kawit, Cavite',startTime:'10:30 AM',endTime:'5:00 PM',courts:5,slotMinutes:15,roundRobinStartMinutes:630,roundRobinWaves:19},clubs:[{id:'ocpc',name:'One Cavite Pickleball Club',short:'OCPC',pairPrefix:'O'},{id:'rebels',name:'Rally Rebels Club',short:'Rally Rebels',pairPrefix:'R'}],categories:['Novice','Low Intermediate','High Intermediate'],pairsPerCategory:{Novice:{ocpc:6,rebels:6},'Low Intermediate':{ocpc:6,rebels:7},'High Intermediate':{ocpc:6,rebels:6}},scoring:{type:'Side-out scoring',target:11,hardCap:11,note:'Side-out scoring to 11, win by 2. At 10-10, play one sudden-death point to decide the match.',warningSeconds:540,dangerSeconds:840,targetSeconds:900}}}
async function ensureLegacyAccess(){if(!user||!legacyManager())return;const eventRef=doc(db,'tournamentEvents',LEGACY_ID),snap=await getDoc(eventRef),batch=writeBatch(db),allowed=EVENT_ROLES.filter(role=>role!=='owner'),people=superAdmin(user.email)?(await getDocs(collection(db,'players'))).docs.map(item=>({id:item.id,...item.data()})).filter(item=>[...rolesOf(item)].some(role=>allowed.includes(role)||role==='admin')):[{id:user.uid,...profile,email:user.email}],memberIds=new Set(snap.data()?.memberIds||[]),refereeEmails=new Set(snap.data()?.refereeEmails||[]);for(const person of people){const personRoles=[...rolesOf(person)].filter(role=>allowed.includes(role)||role==='admin');if(person.id===user.uid&&superAdmin(user.email))personRoles.push('owner','tournament_admin');const normalizedRoles=[...new Set(personRoles)];if(!normalizedRoles.length)continue;memberIds.add(person.id);if(normalizedRoles.includes('tournament_referee')&&person.email)refereeEmails.add(person.email.toLowerCase());const displayName=[person.firstName,person.lastName].filter(Boolean).join(' ')||person.email,email=String(person.email||'').toLowerCase(),primaryRole=normalizedRoles.includes('owner')?'owner':normalizedRoles[0]||'staff';batch.set(doc(eventRef,'members',person.id),{uid:person.id,email,name:displayName,firstName:person.firstName||'',lastName:person.lastName||'',roles:normalizedRoles,updatedAt:serverTimestamp()},{merge:true});batch.set(doc(db,'tournamentAccess',person.id,'events',LEGACY_ID),{eventId:LEGACY_ID,name:'OCPC x Rally Rebels Club Dual Meet',date:'2026-09-19',venue:'Rally District PH',location:'Kawit, Cavite',status:'upcoming',primary:'#005E89',role:primaryRole,roles:normalizedRoles,updatedAt:serverTimestamp()},{merge:true});if(email)batch.set(doc(db,'tournamentAccountDirectory',email),{uid:person.id,email,name:displayName,firstName:person.firstName||'',lastName:person.lastName||'',updatedAt:serverTimestamp()},{merge:true})}batch.set(eventRef,{ownerId:snap.data()?.ownerId||user.uid,memberIds:[...memberIds],refereeEmails:[...refereeEmails],metadata:{name:'OCPC x Rally Rebels Club Dual Meet',date:'2026-09-19',venue:'Rally District PH',location:'Kawit, Cavite',status:'upcoming'},config:legacyConfig(),updatedAt:serverTimestamp()},{merge:true});await batch.commit()}
async function loadEvents(){if(superAdmin(user?.email)){const snap=await getDocs(collection(db,'tournamentEvents'));events=snap.docs.map(item=>{const data=item.data(),meta=data.metadata||{},roles=item.id===LEGACY_ID?['admin','owner','tournament_admin']:['admin'];return{id:item.id,...meta,name:meta.name||data.config?.event?.name||item.id,date:meta.date||data.config?.event?.date||'',venue:meta.venue||data.config?.event?.venue||'',location:meta.location||data.config?.event?.location||'',primary:data.config?.brand?.primary||'#06658c',competitionType:data.config?.competitionType||'dual-meet',roles}})}else{const snap=await getDocs(collection(db,'tournamentAccess',user.uid,'events'));events=snap.docs.map(item=>({id:item.id,...item.data(),competitionType:item.data().competitionType||'dual-meet'}))}if(tournamentRole()&&!events.some(item=>item.id===LEGACY_ID)){const roles=profileEventRoles();events.push({id:LEGACY_ID,name:'OCPC x Rally Rebels Club Dual Meet',date:'2026-09-19',venue:'Rally District PH',location:'Kawit, Cavite',status:'upcoming',primary:'#005E89',competitionType:'dual-meet',role:roles[0]||'staff',roles})}events.sort((a,b)=>String(b.date).localeCompare(String(a.date)));render()}
function eventRoles(event){const roles=rolesOf(event);if(superAdmin(user?.email)||rolesOf(profile).has('admin'))roles.add('admin');roles.delete('court_manager');return roles}
function toolsFor(event){const roles=eventRoles(event),fullControl=roles.has('owner')||roles.has('admin')||roles.has('tournament_admin'),matchControl=fullControl||roles.has('match_control');return TOOL_DEFINITIONS.filter(tool=>{
  if(tool.role==='control')return matchControl;
  return matchControl||roles.has(tool.role);
}).map(tool=>({...tool,label:tool.id==='control'&&!fullControl?tool.operationalLabel:tool.label}))}
function accessLabels(event){const roles=eventRoles(event),visible=[...roles].filter(role=>ROLE_LABELS[role]);return visible.length?visible.map(role=>`<span class="access-badge">${esc(ROLE_LABELS[role])}</span>`):'<span class="access-badge">Assigned staff</span>'}
function renderTool(tool,event){return `<a class="tool-link tool-${tool.id}" href="${eventLink(event.id,tool.path)}"><span class="tool-icon">${esc(tool.icon)}</span><span><b>${esc(tool.label)}</b><small>${esc(tool.description)}</small></span><i aria-hidden="true">→</i></a>`}
function canManageEvent(event){const roles=eventRoles(event);return superAdmin(user?.email)||roles.has('owner')||roles.has('admin')||roles.has('tournament_admin')}
function eventCard(event){const tools=toolsFor(event),archived=event.status==='archived'||event.archived===true,format=event.competitionType==='standard'?'Standard tournament':'Dual meet',deletable=archived&&event.id!==LEGACY_ID;return `<article class="event-card ${archived?'archived':''}" style="--card-brand:${esc(event.primary||'#06658c')}"><header><span class="status">${esc(archived?'Completed':event.status||'Private event')}</span><span class="event-date">${esc(event.date||'Date to be set')}</span></header><span class="event-format">${esc(format)}</span><h3>${esc(event.name)}</h3><p class="event-location">${esc(event.venue||'Venue to be set')}${event.location?`<br>${esc(event.location)}`:''}</p>${archived?`<p>${deletable?'This tournament is archived. Restore it or permanently delete all of its Matchday data.':'This original workspace can be restored, but it cannot be deleted from Matchday.'}</p>`:`<div class="tool-list">${tools.length?tools.map(tool=>renderTool(tool,event)).join(''):'<p class="no-tools">No tournament tools are assigned to this account.</p>'}</div>`}${canManageEvent(event)?`<div class="event-card-actions"><button class="btn alt" type="button" data-event-lifecycle="${esc(event.id)}" data-next-status="${archived?'completed':'archived'}">${archived?'Unarchive tournament':'Archive tournament'}</button>${deletable?`<button class="btn danger" type="button" data-delete-event="${esc(event.id)}">Delete permanently</button>`:''}</div>`:''}</article>`}
function render(){const create=$('#createTournamentBtn');create.hidden=!organizerApproved();const active=events.filter(event=>event.status!=='archived'&&!event.archived),completed=events.filter(event=>event.status==='archived'||event.archived);$('#tournamentGrid').innerHTML=events.length?`${active.length?`<div class="tournament-group-title"><h3>Active tournaments</h3><span>${active.length}</span></div>${active.map(eventCard).join('')}`:''}${completed.length?`<div class="tournament-group-title"><h3>Completed tournaments</h3><span>${completed.length}</span></div>${completed.map(eventCard).join('')}`:''}`:'<div class="empty-card"><h3>No tournaments yet</h3><p>Your owned and assigned tournaments will appear here.</p></div>';document.querySelectorAll('[data-event-lifecycle]').forEach(button=>button.onclick=()=>setEventLifecycle(button.dataset.eventLifecycle,button.dataset.nextStatus,button));document.querySelectorAll('[data-delete-event]').forEach(button=>button.onclick=()=>deleteArchivedEvent(button.dataset.deleteEvent,button))}
async function setEventLifecycle(eventId,nextStatus,button){const archived=nextStatus==='archived',eventRef=doc(db,'tournamentEvents',eventId);if(!confirm(archived?'Archive this tournament and move it to Completed tournaments?':'Unarchive this tournament and return it to Active tournaments?'))return;button.disabled=true;try{const [eventSnap,membersSnap]=await Promise.all([getDoc(eventRef),getDocs(collection(eventRef,'members'))]),data=eventSnap.data()||{},date=data.config?.event?.date||data.metadata?.date||'',today=new Date().toISOString().slice(0,10),metadata={...(data.metadata||{}),status:archived?'archived':(date&&date>=today?'upcoming':'completed'),archived,archivedAt:archived?new Date().toISOString():null};const batch=writeBatch(db);batch.set(eventRef,{metadata,sessionDeviceId:sessionLock.deviceId(),updatedAt:serverTimestamp()},{merge:true});membersSnap.docs.forEach(member=>batch.set(doc(db,'tournamentAccess',member.id,'events',eventId),{status:metadata.status,archived,archivedAt:metadata.archivedAt,competitionType:data.config?.competitionType||'dual-meet',updatedAt:serverTimestamp()},{merge:true}));await batch.commit();await loadEvents()}catch(error){console.error(error);button.disabled=false;alert('The tournament status could not be updated. Check your connection and try again.')}}
async function deleteRefs(refs){for(let offset=0;offset<refs.length;offset+=400){const batch=writeBatch(db);refs.slice(offset,offset+400).forEach(ref=>batch.delete(ref));await batch.commit()}}
async function deleteArchivedEvent(eventId,button){const listed=events.find(item=>item.id===eventId),archived=listed&&(listed.status==='archived'||listed.archived===true);if(!listed||!archived||eventId===LEGACY_ID)return alert('Only archived tournaments can be permanently deleted.');const answer=prompt(`Permanently delete "${listed.name||eventId}"? This removes registrations, check-ins, results, staff access, and its live public link. This cannot be undone.\n\nType DELETE to continue.`);if(answer!=='DELETE')return;button.disabled=true;button.textContent='Deleting…';try{const eventRef=doc(db,'tournamentEvents',eventId),eventSnap=await getDoc(eventRef);if(!eventSnap.exists()){events=events.filter(item=>item.id!==eventId);render();return}const data=eventSnap.data()||{},metadata=data.metadata||{};if(metadata.archived!==true&&metadata.status!=='archived')throw new Error('NOT_ARCHIVED');const [members,matches,registrations,checkins,refereeBoard]=await Promise.all([getDocs(collection(eventRef,'members')),getDocs(collection(eventRef,'matches')),getDocs(collection(eventRef,'registrations')),getDocs(collection(eventRef,'checkins')),getDoc(doc(db,'tournamentRefereeBoards',eventId))]);const currentMember=members.docs.find(member=>member.id===user.uid),memberIds=new Set([...(Array.isArray(data.memberIds)?data.memberIds:[]),...members.docs.map(member=>member.id)]),cleanup=[...matches.docs.map(item=>item.ref),...registrations.docs.map(item=>item.ref),...checkins.docs.map(item=>item.ref),...members.docs.filter(member=>member.id!==user.uid).map(member=>member.ref),...[...memberIds].map(uid=>doc(db,'tournamentAccess',uid,'events',eventId))];await deleteRefs(cleanup);const publicToken=data.state?.publicShare?.token;if(publicToken)await deleteDoc(doc(db,'tournamentPublicViews',publicToken));if(refereeBoard.exists())await deleteDoc(refereeBoard.ref);await deleteDoc(eventRef);if(currentMember)await deleteDoc(currentMember.ref);events=events.filter(item=>item.id!==eventId);render()}catch(error){console.error(error);button.disabled=false;button.textContent='Delete permanently';alert(error?.message==='NOT_ARCHIVED'?'This tournament is no longer archived. Refresh and try again.':'The tournament could not be fully deleted. Its archived record remains so you can safely retry.')}}
async function renderPlatformAdmin(){document.querySelector('.platform-admin')?.remove();if(!superAdmin(user?.email))return;const snapshot=await getDocs(collection(db,'tournamentOrganizerApplications')),items=snapshot.docs.map(item=>({id:item.id,...item.data()})).filter(item=>item.status==='pending'),section=document.createElement('section');section.className='platform-admin';section.innerHTML='<header><div><span class="eyebrow">Platform super admin</span><h2>Organizer approvals</h2></div><span>'+items.length+' pending</span></header>'+(items.length?items.map(item=>'<article><div><b>'+esc(item.displayName||item.email)+'</b><small>'+esc(item.organizationName||'Organization not supplied')+' · '+esc(item.email)+'</small></div><button class="btn lime" data-approve-organizer="'+item.id+'">Approve</button><button class="btn alt" data-reject-organizer="'+item.id+'">Reject</button></article>').join(''):'<p>No organizer applications are waiting.</p>');document.querySelector('.portal-toolbar').after(section);section.querySelectorAll('[data-approve-organizer],[data-reject-organizer]').forEach(button=>button.onclick=async()=>{const uid=button.dataset.approveOrganizer||button.dataset.rejectOrganizer,status=button.dataset.approveOrganizer?'approved':'rejected',batch=writeBatch(db);button.disabled=true;batch.update(doc(db,'tournamentOrganizerApplications',uid),{status,reviewedBy:user.uid,reviewedAt:serverTimestamp(),updatedAt:serverTimestamp()});batch.update(doc(db,'tournamentUsers',uid),{organizerStatus:status,platformRole:status==='approved'?'organizer':'user',updatedAt:serverTimestamp()});await batch.commit();await renderPlatformAdmin()})}
$('#portalLogin').onsubmit=async event=>{event.preventDefault();$('#loginError').textContent='Signing in…';try{await setPersistence(auth,browserLocalPersistence);await signInWithEmailAndPassword(auth,$('#portalEmail').value.trim(),$('#portalPassword').value)}catch(_){$('#loginError').textContent='The email or password is incorrect, or this account is not approved.'}};
$('#portalLogout').onclick=async()=>{await sessionLock.release();await signOut(auth)};$('#createTournamentBtn').onclick=()=>$('#createModal').hidden=false;$('#closeCreate').onclick=()=>$('#createModal').hidden=true;$('#createModal').onclick=event=>{if(event.target===$('#createModal'))$('#createModal').hidden=true};onAuthStateChanged(auth,current=>{if(current&&superAdmin(current.email))setTimeout(()=>renderPlatformAdmin().catch(()=>{}),1200)});
$('#openTournamentSignup').onclick=()=>$('#signupModal').hidden=false;$('#closeTournamentSignup').onclick=()=>$('#signupModal').hidden=true;$('#signupModal').onclick=event=>{if(event.target===$('#signupModal'))$('#signupModal').hidden=true};$('#signupOrganizer').onchange=()=>{$('#organizationNameLabel').hidden=!$('#signupOrganizer').checked;$('#signupOrganization').required=$('#signupOrganizer').checked};
$('#tournamentSignupForm').onsubmit=async event=>{event.preventDefault();const error=$('#signupError'),email=$('#signupEmail').value.trim().toLowerCase(),name=$('#signupName').value.trim(),organizer=$('#signupOrganizer').checked;error.textContent='Creating secure tournament account…';try{await setPersistence(auth,browserLocalPersistence);const credential=await createUserWithEmailAndPassword(auth,email,$('#signupPassword').value);const base={uid:credential.user.uid,email,displayName:name,accountStatus:'active',platformRole:'user',organizerStatus:organizer?'pending':'none',createdAt:serverTimestamp(),updatedAt:serverTimestamp()},batch=writeBatch(db);batch.set(doc(db,'tournamentUsers',credential.user.uid),base);batch.set(doc(db,'tournamentAccountDirectory',email),{uid:credential.user.uid,email,name,updatedAt:serverTimestamp()});if(organizer)batch.set(doc(db,'tournamentOrganizerApplications',credential.user.uid),{applicantUid:credential.user.uid,email,displayName:name,organizationName:$('#signupOrganization').value.trim(),status:'pending',submittedAt:serverTimestamp(),updatedAt:serverTimestamp()});await batch.commit();$('#signupModal').hidden=true}catch(errorObject){error.textContent=errorObject.code==='auth/email-already-in-use'?'That email already has an account. Sign in instead.':'Account could not be created. Check the form and try again.'}};
function ensurePairingFields(){const standardFormat=$('#newStandardFormat');if(!standardFormat)return;const pairLabel=$('#newExpectedPairs')?.closest('label');if(pairLabel&&!pairLabel.id)pairLabel.id='newExpectedPairsField';if(!$('#newPairingMode')){const modeLabel=document.createElement('label');modeLabel.innerHTML='Registration model<select id="newPairingMode"><option value="fixed-pairs">Register fixed pairs</option><option value="random-partners">Register individuals → draw fixed partners on event day</option></select><small id="newPairingHint">Players arrive already paired. Registration Desk records each pair and its pair name.</small>';pairLabel?.before(modeLabel)}if(!$('#newExpectedPlayers')){const playersLabel=document.createElement('label');playersLabel.id='newExpectedPlayersField';playersLabel.hidden=true;playersLabel.innerHTML='Expected players per category<input id="newExpectedPlayers" type="number" min="4" max="128" step="2" value="24"><small>Must be an even number. One draw creates fixed pairs for the entire tournament.</small>';pairLabel?.after(playersLabel)}$('#newPairingMode').oninput=setCreateMode}
function selectedCompetitionType(){return document.querySelector('[name="competitionType"]:checked')?.value||'dual-meet'}
function setCreateMode(){ensurePairingFields();const standard=selectedCompetitionType()==='standard',random=standard&&$('#newPairingMode')?.value==='random-partners';$('#dualMeetFields').hidden=standard;$('#standardFields').hidden=!standard;$('#newClub1').required=!standard;$('#newClub2').required=!standard;$('#newAffiliations').required=false;if(standard&&$('#newCategories').value==='Novice, Low Intermediate, High Intermediate')$('#newCategories').value='Novice Mixed Doubles';if(!standard&&$('#newCategories').value==='Novice Mixed Doubles')$('#newCategories').value='Novice, Low Intermediate, High Intermediate';if($('#newExpectedPairsField'))$('#newExpectedPairsField').hidden=random;if($('#newExpectedPlayersField'))$('#newExpectedPlayersField').hidden=!random;if($('#newPairingHint'))$('#newPairingHint').textContent=random?'Players register one at a time. Matchday draws partners once before play, lets the organizer review or reshuffle, then locks the same fixed pairs for every match.':'Players arrive already paired. Registration Desk records each pair and its pair name.';renderFormatEstimate()}
document.querySelectorAll('[name="competitionType"]').forEach(input=>input.onchange=setCreateMode);setCreateMode();
function affiliationList(){const names=$('#newAffiliations').value.split(',').map(value=>value.trim()).filter(Boolean),used=new Set();if(!names.length)return[{id:'unaffiliated',name:'Unaffiliated',short:'Unaffiliated',pairPrefix:'U'}];return names.map((name,index)=>{let id=slug(name)||`affiliation-${index+1}`,suffix=2;while(used.has(id))id=`${slug(name)}-${suffix++}`;used.add(id);return{id,name,short:name,pairPrefix:String.fromCharCode(65+index%26)}})}
function standardPairCounts(affiliations,total){const base=Math.floor(total/affiliations.length),extra=total%affiliations.length;return Object.fromEntries(affiliations.map((item,index)=>[item.id,Math.max(0,base+(index<extra?1:0))]))}
function setupValues(){
  const format=$('#newStandardFormat').value, pairingMode=$('#newPairingMode')?.value||'fixed-pairs', randomPartners=pairingMode==='random-partners', expectedPlayers=randomPartners?Number($('#newExpectedPlayers').value):null, expectedPairs=randomPartners?expectedPlayers/2:Number($('#newExpectedPairs').value);
  if(randomPartners&&(!Number.isInteger(expectedPlayers)||expectedPlayers<4||expectedPlayers>128||expectedPlayers%2!==0))throw new Error('Enter an even number of expected players (4–128) for random partner assignment.');
  const poolCount=Number($('#newPoolCount').value), qualifiers=Number($('#newQualifiers').value);
  const matchMinutes=Number($('#newMatchMinutes').value), medalMinutes=Number($('#newMedalMinutes').value), turnover=Number($('#newTurnoverMinutes').value);
  if(![matchMinutes,medalMinutes].every(n=>Number.isInteger(n)&&n>=1&&n<=180)||!Number.isInteger(turnover)||turnover<0||turnover>30)throw new Error('Enter valid whole-minute match and turnover durations.');
  const division=buildStandardDivision({format,expectedPairs,poolCount,qualifiers,
    ...(format==='pools-elimination'?{qualifiersPerPool:Number($('#newPerPool').value)}:{}),bronzeMatch:$('#newBronze').checked});
  return {division,matchMinutes,medalMinutes,turnover,timed:$('#newScoring').value==='timed-rally',pairingMode,expectedPlayers};
}
function buildTournamentConfig(){
  const competitionType=selectedCompetitionType(),name=$('#newName').value.trim(),date=$('#newDate').value;
  const start=$('#newStart').value,end=$('#newEnd').value,primary=$('#newColor').value;
  const categories=[...new Set($('#newCategories').value.split(',').map(value=>value.trim()).filter(Boolean))];
  if(!categories.length)throw new Error('Add at least one category.');
  if(minutes(end)<=minutes(start))throw new Error('End time must be later than start time on the same day.');
  const courts=Number($('#newCourts').value);
  if(!Number.isInteger(courts)||courts<1||courts>24)throw new Error('Choose 1 to 24 courts.');
  const standard=competitionType==='standard',setup=standard?setupValues():null;
  const affiliations=standard?affiliationList():[
    {id:'ocpc',name:$('#newClub1').value.trim(),short:$('#newClub1').value.trim(),pairPrefix:'O'},
    {id:'rebels',name:$('#newClub2').value.trim(),short:$('#newClub2').value.trim(),pairPrefix:'R'}];
  const scoring=setup?.timed?{mode:'timed-rally',type:'Timed rally scoring',target:null,hardCap:null,matchMinutes:setup.matchMinutes,medalMinutes:setup.medalMinutes,targetSeconds:setup.matchMinutes*60,warningSeconds:Math.max(0,setup.matchMinutes-2)*60,dangerSeconds:setup.matchMinutes*60,note:'Every rally scores. At the time limit, the higher score wins; a tied score requires a deciding rally.'}:
    {type:'Side-out scoring',target:11,hardCap:11,matchMinutes:setup?.matchMinutes||15,note:'Side-out scoring to 11; sudden death at 10–10. Standard championship: win by 2, cap 15, no timer.',warningSeconds:540,dangerSeconds:840,targetSeconds:(setup?.matchMinutes||15)*60};
  return {appName:'Matchday',competitionType,schemaVersion:standard?15:13,
    brand:{organizer:$('#newOrganizer').value.trim(),shortName:$('#newOrganizer').value.trim().slice(0,16),logo:'/tournament/assets/matchday-mark.svg',primary,primaryDark:'#06364D',accent:'#4FB6FF',highlight:'#B6FF3C',gold:'#FFC24B'},
    event:{name,date,displayDate:new Date(date+'T12:00:00').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}),venue:$('#newVenue').value.trim(),location:$('#newLocation').value.trim(),startTime:timeLabel(start),endTime:timeLabel(end),courts,slotMinutes:setup?Math.max(5,setup.matchMinutes+setup.turnover):15,roundRobinStartMinutes:minutes(start),roundRobinWaves:1},
    clubs:affiliations,affiliations,categories,
    pairsPerCategory:Object.fromEntries(categories.map(category=>[category,standard?standardPairCounts(affiliations,setup.division.entryLimit):{ocpc:6,rebels:6}])),
    pairing:standard?{mode:setup.pairingMode,registrationUnit:setup.pairingMode==='random-partners'?'individual':'pair',algorithm:setup.pairingMode==='random-partners'?'crypto-fisher-yates':null,lockRequired:setup.pairingMode==='random-partners',fixedAfterLock:setup.pairingMode==='random-partners',expectedPlayers:setup.expectedPlayers||setup.division.entryLimit*2,expectedPairs:setup.division.entryLimit,status:setup.pairingMode==='random-partners'?'unlocked':'not-applicable'}:{mode:'fixed-pairs',registrationUnit:'pair'},
    divisions:standard?categories.map((category,index)=>({...setup.division,id:'division-'+(index+1)+'-'+slug(category),name:category,category,scoring:setup.timed?{target:9999,winBy:1,hardCap:9999}:{target:11,winBy:2,hardCap:11}})):[],
    ...(standard?{standardScheduling:{dispatchMode:'fixed-sequence',startMinutes:minutes(start),endMinutes:minutes(end),slotMinutes:Math.max(5,setup.matchMinutes+setup.turnover),matchMinutes:setup.matchMinutes,medalMinutes:setup.medalMinutes,turnoverMinutes:setup.turnover,estimateSlotVersion:2}}:{}),
    capabilities:standard?{clubChampionship:false,dreamBreaker:false,opponentDraw:false,pools:true,dynamicBracket:true}:{clubChampionship:true,dreamBreaker:true,opponentDraw:true,pools:false,dynamicBracket:false},scoring};
}
function renderFormatEstimate(){
  const target=$('#newFormatEstimate');if(!target)return;
  const pools=$('#newStandardFormat').value==='pools-elimination';
  $('#poolFields').hidden=!pools;$('#newQualifiers').closest('label').hidden=pools;
  try{
    const {division,matchMinutes,medalMinutes,turnover,timed,pairingMode,expectedPlayers}=setupValues(), pairs=division.entryLimit;
    const counts=Object.values(standardPairCounts(affiliationList(),pairs));
    const sizes=pools?Array.from({length:division.poolCount},(_,i)=>Math.floor(pairs/division.poolCount)+(i<pairs%division.poolCount?1:0)):[pairs];
    const cross=division.format.startsWith('cross-affiliation');
    const preliminary=division.format==='single-elimination'?0:sizes.reduce((n,size)=>n+size*(size-1)/2,0)-(cross?counts.reduce((n,size)=>n+size*(size-1)/2,0):0);
    const q=division.format==='single-elimination'?pairs:pools?division.poolCount*division.qualifiers.perPool+division.qualifiers.wildcards:division.qualifiers?.count||0;
    const elimination=Math.max(0,q-1)+(division.bronzeMatch&&q>=4?1:0),total=preliminary+elimination;
    const courts=Math.max(1,Number($('#newCourts').value)||1);
    const poolWaves=pools?Math.max(...sizes.map(n=>n%2?n:n-1)):0;
    const prelimWaves=Math.max(Math.ceil(preliminary/courts),poolWaves);
    let bracketWaves=0;for(let n=2**Math.ceil(Math.log2(q||1));n>1;n/=2)bracketWaves+=Math.ceil((n===2&&division.bronzeMatch&&q>=4?2:n/2)/courts);
    const medalWaves=q>=2?Math.ceil((division.bronzeMatch&&q>=4?2:1)/courts):0;
    const estimate=(prelimWaves+bracketWaves-medalWaves)*(matchMinutes+turnover)+medalWaves*(medalMinutes+turnover);
    const windowMinutes=minutes($('#newEnd').value)-minutes($('#newStart').value);
    target.innerHTML='<b>'+total+' matches per category</b>'+preliminary+' preliminary + '+elimination+' knockout / medal matches. '+(pairingMode==='random-partners'?expectedPlayers+' individual registrations → '+pairs+' pairs after the locked draw. ':'')+(pools?division.poolCount+' pools · '+division.qualifiers.perPool+' qualifier(s) per pool. ':'')+(timed?'About '+estimate+' minutes of court slots per category, before additional rest, briefing or delays. '+(windowMinutes>0?'Your venue window: '+windowMinutes+' minutes. ':''):'Side-out medal matches have no timer; finish time cannot be guaranteed. ')+'Set pairs and publish the draw before play.';
  }catch(error){target.textContent=error.message}
}
ensurePairingFields();
['newExpectedPairs','newExpectedPlayers','newPairingMode','newQualifiers','newStandardFormat','newAffiliations','newPoolCount','newPerPool','newBronze','newScoring','newMatchMinutes','newMedalMinutes','newTurnoverMinutes','newCourts','newStart','newEnd'].forEach(id=>{const element=$('#'+id);if(!element)return;element.addEventListener('input',renderFormatEstimate);element.addEventListener('change',renderFormatEstimate)});
$('#birthdayPreset').onclick=()=>{
  document.querySelector('[name="competitionType"][value="standard"]').checked=true;
  const values={newCourts:2,newStart:'20:00',newEnd:'22:00',newStandardFormat:'pools-elimination',newPairingMode:'random-partners',newExpectedPairs:12,newExpectedPlayers:24,newPoolCount:4,newPerPool:1,newQualifiers:4,newScoring:'timed-rally',newMatchMinutes:8,newMedalMinutes:10,newTurnoverMinutes:2,newCategories:'Open Doubles',newAffiliations:''};
  Object.entries(values).forEach(([id,value])=>$('#'+id).value=value);$('#newBronze').checked=true;setCreateMode();
  $('#newName').focus();
};
renderFormatEstimate();
$('#createTournamentForm').onsubmit=async event=>{event.preventDefault();if(!organizerApproved())return $('#createError').textContent='Platform administrator approval is required before creating tournaments.';const submit=event.submitter||$('#createTournamentForm button[type="submit"]');if(submit.disabled)return;let config;try{config=buildTournamentConfig()}catch(error){$('#createError').textContent=error.message;return}const name=config.event.name,date=config.event.date,eventId=`${slug(name)}-${date}-${crypto.getRandomValues(new Uint16Array(1))[0].toString(16)}`;if(config.competitionType==='standard'&&config.divisions.some(division=>division.format.startsWith('cross-affiliation'))&&config.affiliations.length<2)return $('#createError').textContent='Add at least two teams or affiliations for a cross-team round robin.';config.firebaseEventId=eventId;config.storageKey=`matchday.${eventId}`;submit.disabled=true;$('#createError').textContent='Creating private workspace…';try{const eventRef=doc(db,'tournamentEvents',eventId),batch=writeBatch(db),ownerRoles=['owner','tournament_admin'],metadata={name,date,venue:config.event.venue,location:config.event.location,status:'draft',primary:config.brand.primary,competitionType:config.competitionType,archived:false};batch.set(eventRef,{ownerId:user.uid,memberIds:[user.uid],refereeEmails:[],metadata,config,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});batch.set(doc(eventRef,'members',user.uid),{uid:user.uid,email:user.email.toLowerCase(),name:[profile?.firstName,profile?.lastName].filter(Boolean).join(' ')||user.email,roles:ownerRoles,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});batch.set(doc(db,'tournamentAccess',user.uid,'events',eventId),{eventId,...metadata,role:'owner',roles:ownerRoles,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await batch.commit();location.href=eventLink(eventId)}catch(error){console.error(error);$('#createError').textContent='Tournament could not be created. Check Firebase access and try again.'}finally{submit.disabled=false}};
let portalLoadAttempt=0;
async function openPortal(current){
  const attempt=++portalLoadAttempt;
  user=current; profile=null; events=[];
  // Listing already-authorized tournaments does not require a device lease.
  // Each operational app verifies that lease before enabling its controls.
  $('#loginGate').hidden=Boolean(current);
  $('#portalWorkspace').hidden=!current;
  $('#createTournamentBtn').hidden=true;
  if(!current)return;
  $('#portalIdentity').textContent=current.email;
  $('#tournamentGrid').innerHTML='<div class="empty-card" role="status"><h3>Loading your tournaments…</h3><p>You are signed in.</p></div>';
  const slow=setTimeout(()=>{
    if(attempt!==portalLoadAttempt)return;
    $('#tournamentGrid').innerHTML='<div class="empty-card" role="status"><h3>Still connecting to your tournaments</h3><p>Your account is signed in. Check your connection and retry.</p><button class="btn" id="retryPortal">Retry loading</button></div>';
    $('#retryPortal').onclick=()=>openPortal(auth.currentUser);
  },12000);
  try{
    const [tournamentSnap,playerSnap]=await Promise.all([
      getDoc(doc(db,'tournamentUsers',current.uid)).catch(()=>null),
      getDoc(doc(db,'players',current.uid)).catch(()=>null)
    ]);
    if(attempt!==portalLoadAttempt)return;
    const legacy=playerSnap?.exists()?playerSnap.data():{},tournament=tournamentSnap?.exists()?tournamentSnap.data():{};
    profile={...legacy,...tournament,roles:[...rolesOf(legacy),...rolesOf(tournament)]};
    await loadEvents();
    if(attempt!==portalLoadAttempt)return;
    // This optional directory refresh must never block cached/online reads.
    if(navigator.onLine!==false)ensureSelfDirectory().catch(error=>console.warn('Directory refresh deferred.',error));
    const destination=safeReturn();
    if(destination)location.replace(destination);
    else if(new URLSearchParams(location.search).has('denied'))$('#tournamentGrid').insertAdjacentHTML('afterbegin','<div class="empty-card warning-card"><h3>That tournament is not assigned to this account</h3><p>Choose an event below or ask its owner to grant access.</p></div>');
  }catch(error){
    if(attempt!==portalLoadAttempt)return;
    console.error('Tournament list could not load.',error);
    $('#tournamentGrid').innerHTML='<div class="empty-card" role="alert"><h3>Your tournaments could not load</h3><p>You are signed in. Check your connection and retry.</p><button class="btn" id="retryPortal">Retry loading</button></div>';
    $('#retryPortal').onclick=()=>openPortal(auth.currentUser);
  }finally{clearTimeout(slow)}
}
onAuthStateChanged(auth,openPortal);

document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(!$('#createModal').hidden){$('#createModal').hidden=true;$('#createTournamentBtn').focus()}if(!$('#signupModal').hidden){$('#signupModal').hidden=true;$('#openTournamentSignup').focus()}}});
